requirements.txt

uuid 1.30 is not support Python3.
So used uuid of stdlib.

Delite uuid lib of requirements.txt. 

---

src/handlers/articles/recent/articles_recent.py
tests/handlers/articles/recent/test_articles_recent.py

* Fix error that raise when no query parameters.
* Use `self.params`.

ALIS-357: Fix bug with no-query-params

---

src/common/settings.py
src/handlers/cognito_trigger/presignup/handler.py
src/handlers/cognito_trigger/presignup/pre_signup.py
template.yaml.tpl
tests/handlers/cognito_trigger/presignup/test_pre_signup.py
tests/handlers/users/articles/public/test_users_articles_public.py

signup時のユーザーID名のチェックを追加
* 3文字以上30文字以下
* 半角英数字とハイフンのみ使用可能
* 先頭と末尾にハイフンは使用不可
* 連続したハイフンは使用不可
* [登録させたくないID](https://qiita.com/phimcall/items/4c559b70f70ea7f1953b)はNG

ALIS-341: add user_id validation

---

src/handlers/cognito_trigger/custommessage/custom_message.py

パスワードリセット時も電話番号の存在確認をして、エラーになるのを修正
（phone_number_verifiedがtrueの時はチェックしない）

don't check phone number when it already verified

---

src/handlers/me/articles/drafts/create/me_articles_drafts_create.py
src/handlers/me/articles/drafts/update/me_articles_drafts_update.py
src/handlers/me/articles/public/update/me_articles_public_update.py
tests/handlers/me/articles/drafts/create/test_me_article_drafts_create.py
tests/handlers/me/articles/drafts/update/test_me_articles_drafts_update.py
tests/handlers/me/articles/public/update/test_me_articles_public_update.py

* Fix bug with empty string parameter
* If there is empty string in parameter, it'll be converted None.
* DynamoDB does not suport empty string

ALIS-649: Fix bug with empty string parameter

---

src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py

* 公開日順に記事がソートされるように修正
* 初回公開時にpublished_at(公開日)を追加
* 表示用のカラム
* 初回公開時にsort_keyをupdate
* 表示する日付をpublished_atに変更する必要がある。（下書き記事一覧はcreated_atのままで良い）
* データ以降
* published_atが保存されていない記事の扱いを決めて、実行する

ALIS-799: Update sort_key and add published_at when article publish

---

src/common/text_sanitizer.py
tests/common/test_text_sanitizer.py

twitter embedded 対応
* 環境変数に変更を加えたか否か
なし
ALIS利用ユーザ
- サーバレス
- フロントエンド
* サニタイジング処理で div タグの data-alis-iframely-url 属性のチェック処理を追加（twitter.comのみ許可）
なし
なし
変更なし
500 系の場合にはエラーを出力

ALIS-897: Modify to allow twitter

---

src/common/text_sanitizer.py
tests/common/test_text_sanitizer.py

twitter embedded 対応のため #104 にてサニタイズ処理修正を行ったが追加で許可すべき属性（contenteditable='false'）が増えたため対応
* 環境変数に変更を加えたか否か
なし
ALIS利用ユーザ
- サーバレス
- フロントエンド
* サニタイジング処理で div タグの data-alis-iframely-url 属性のチェック処理を追加（twitter.comのみ許可）
なし
なし
変更なし
500 系の場合にはエラーを出力

ALIS-925: Add pattern of sanitize for div

---

src/handlers/me/articles/drafts/index/me_articles_drafts_index.py
src/handlers/me/articles/public/index/me_articles_public_index.py
src/handlers/users/articles/public/users_articles_public.py
tests/handlers/me/articles/drafts/index/test_me_article_drafts_index.py
tests/handlers/me/articles/public/index/test_me_articles_public_index.py
tests/handlers/users/articles/public/test_users_articles_public.py

* 自分の記事一覧や特定ユーザの記事一覧などでLimitの数以上に対象の記事があるにもかかわらずLimit以下の件数が返ってくることがあった。
* DynamoDBのLimitはFilterを行う前に実行されるため。
* 公開記事と下書きはFilterで絞り込んでいるため、Limitの件数を取ってきた後にその中から公開or下書きのみのフィルタリングを行ってしまう。（結果として7件とかになってしまう）
* EvaluatedKeyが存在する（ページネーションの途中）、かつFilter済みの件数がlimit以下の場合はlimitに達するまで同じ処理を繰り返し、結果を返すように修正する。
* なし
* 特になし
* エンドユーザー全員
- サーバレス
- フロントエンド(基本的には変わらないはずだが)
* なにをどう変更したか
* 特になし
* Limitに達するまでなんども実行されるためクエリの本数は増える。
* が、基本的にはユーザーで絞っている記事に対してのクエリのため数百件実行される、というようなことはないのでパフォーマンス懸念はなしと判断。
* なし
* なし
* なし
* コード参照
（下書き、公開合わせて10件以上存在する状態でテスト）
* 公開/非公開/非公開/非公開/非公開/非公開/非公開/非公開/非公開/非公開/公開 の状態で公開/公開が取得できることを確認
* 非公開/公開/公開/公開/公開/公開/公開/公開/公開/公開/非公開 の状態で非公開/非公開が取得できることを確認

ALIS-912: Fix limit of index my aritcles

---

src/handlers/articles/popular/articles_popular.py
tests/handlers/articles/popular/test_articles_popular.py

人気記事一覧では常に最新のevaluated_keyを参照し、Queryのkeyに指定していた。
その結果ページネート途中で人気集計バッチが実行された場合、パラメータで渡されるLastEvaluatedKeyのevaluated_atとQueryの検索軸で使われるevaluated_atが異なることになり、例外が発生していた。
上記を解消するために、LastEvaluatedKeyがパラメータで渡ってきている（ページネーションの振る舞いを期待している）場合にはパラメータで渡ってきた値を正としてQueryの検索条件に利用するようにした。
変更なし
特になし
* エンドユーザー
- サーバレス
* ページネーション用の分岐の中で、パラメータのQueryの検索条件をUpdateしている。
特になし
発行されるクエリには変更なし
影響なし
なし
なし
* 概要で説明したようなシナリオをケースとして追加している

ALIS-956: Use request param's evaluated_at when last evaluated key is present

---

database-template.yaml

- ALIS-938追加時の細かいfixでございます。
- DBはCloudFromation管理から外したため開発環境を優先し `DeletionPolicy` を除却した
- CloudFromationテンプレートのJinja2による管理は廃止したためJinja2の書式は無効となりました
- `{{ ... ]]` というやつです

Fix a little bit

---

api-template.yaml
src/handlers/me/unread_notification_managers/update/me_unread_notification_managers_update.py
tests/handlers/me/unread_notification_managers/update/test_me_unread_notification_managers_update.py

* 通知機能用の未読管理を更新するLambdaの実装zipの名前が間違っていたため修正
* 未読管理用の更新APIのBooleanが逆だったので修正 🙇

Fix deploy zip file name

---

database-template.yaml
database.yaml
src/common/settings.py
src/handlers/me/articles/like/create/me_articles_like_create.py
src/handlers/me/notifications/index/me_notifications_index.py
tests/handlers/me/articles/like/create/test_me_articles_like_create.py
tests/handlers/me/notifications/index/test_me_notifications_index.py

* 通知機能の要件変更を吸収する形でAPIを修正した。具体的には以下の２点
* 誰がいいねをしたのかを保存しないようにした
* サマって表示できるようにした
特になし
* エンドユーザ
- サーバレス
- フロントエンド
* いいね実施時に常にレコードの追加をするのではなく、該当のユーザーの該当の記事のいいねに関する通知レコードがある場合は値をインクリメントするように修正
* インクリメントと書いたが、厳密には最新のいいね数をDBアクセスして取ってきてその数値に+1したものを挿入している
* primary_keyにnotification_idというものを指定するように修正したので、user_idとsort_keyでqueryできるようにindexを指定するように修正した
* 変更点
* primaryをuser_id + sort_keyから notification_idに変更
* さらにuser_idとsort_keyのindexを作成
* なぜprimaryを変更する必要があるか
* サマり表示を実現するために、イミュータブルなデータから、ミュータブルデータとして扱う必要が出てきたため。primaryキーは更新できない。
なし
特になし

Modify feature notification

---

src/common/text_sanitizer.py
tests/common/test_text_sanitizer.py

div タグのサニタイズ処理に過不足があったため修正
追加：medium-insert-images medium-insert-images-wide
削除：medium-insert-images medium-insert-active
* 記事投稿を行うユーザ
- サーバレス
* div タグのクラス属性のサニタイズ処理を修正
* テストコード記載済

ALIS-1001: Fix config of sanitize for div

---

src/common/text_sanitizer.py
tests/common/test_text_sanitizer.py

* OGP対応のため sanitize 条件を変更
* 環境変数の変更無し
* ログインユーザ（投稿者）
- サーバレス
- フロントエンド
* div タグの data-alis-iframely-url 属性について全URLを許可（ただしタグ値は除去）
なし
なし
なし
* ユニットテストが書かれているか
書いている

Modify config of sanitize for OGP

---

src/common/lambda_base.py

* 画像ファイルのアップロードに失敗する問題に対応するため、4XX系のエラーでも入力値をログに出力するように修正
　
* ALIS利用ユーザ
- サーバレス
* 4xx 系のエラーが発生した際にも入力をログに出力するように修正
* ログは cloudwatch logs に出力される

ALIS-1076: Add logs for 4xx

---

src/handlers/me/articles/images/create/me_articles_images_create.py
src/handlers/me/info/icon/create/me_info_icon_create.py
tests/handlers/me/articles/images/create/test_me_articles_images_create.py
tests/handlers/me/info/icon/create/test_me_info_icon_create.py

* 画像ファイルアップロードを失敗している場合、content-type がアッパーケース（Content-Tytpe）で連携されていることが確認できたため、アッパーケースにも対応できるよう修正。
※ 既に develop ブランチに同様の pull request を投げているが、この修正のみ優先してリリースしたいため、master から切り出した develop_fix_img_upload ブランチにて対応。
* ログインユーザ
- サーバレス
- フロントエンド
content-type がアッパーケース（Content-Tytpe）でも動くように、チェック処理や値の取得処理を修正。
* ユニットテストは記載済み

Add pattern of Content-Type for sanitizing

---

api-template.yaml
src/handlers/me/articles/comments/create/me_articles_comments_create.py
tests/handlers/me/articles/comments/create/test_me_articles_comments_create.py

* コメントを作成する際に返却値として何も返さないと、ajaxで描画する際にcomment_idをセットできない
* するとそのコメントを削除しようとした時にcomment_idが指定できずにエラーになってしまう問題があった
* 上記問題を解決するためにコメントの作成時にcomment_idを返却するように修正
* 上記修正に紐づく、テスト、swaggerの修正
* コメントの作成時にcomment_idを返却するように修正
* 使い方の説明
* バグの場合は再現条件
* 特になし

Return comment_id when comment created

---

src/common/text_sanitizer.py
tests/common/test_text_sanitizer.py

* テキストのsanitizingで利用しているbleachのcleanメソッドだが、デフォルトでいくつかのタグは許容してしまっていた。
* https://bleach.readthedocs.io/en/latest/clean.html#allowed-tags-tags
* 上記を修正するために明示的に全てのタグをsanitizeするように指定した。
* `sanitize_text ` を利用している箇所を確認したが、全てHTMLタグは一律sanitizeしたいケースでの利用だったので、メソッドの振る舞いを変えることの影響はないと判断している。

Sanitize all tags

---

.circleci/config.yml
Dockerfile
README.md
api-template.yaml
database-template.yaml
database.yaml
elasticsearch-setup.py
requirements.txt
src/common/es_util.py
src/common/lambda_base.py
src/handlers/cognito_trigger/postconfirmation/post_confirmation.py
src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py
src/handlers/me/articles/public/republish/me_articles_public_republish.py
src/handlers/me/articles/public/unpublish/me_articles_public_unpublish.py
src/handlers/me/info/update/me_info_update.py
src/handlers/search/articles/handler.py
src/handlers/search/articles/search_articles.py
src/handlers/search/users/handler.py
src/handlers/search/users/search_users.py
tests/handlers/cognito_trigger/postconfirmation/test_post_confirmation.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py
tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py
tests/handlers/me/articles/public/unpublish/test_me_articles_public_unpublish.py
tests/handlers/me/info/update/test_me_info_update.py
tests/handlers/search/articles/test_search_articles.py
tests/handlers/search/users/test_search_users.py

Elasticsearchによる全文検索処理を追加
* 環境変数
* ELASTIC_SEARCH_ENDPOINT を追加
* SSMパラメータ
* ElasticSearchEndpoint を追加
* ElasticSearchAccessRole を追加
記事を見るユーザー: 記事を検索できるようになる
- サーバレス
- フロントエンド
* Elasticsearchと同期する処理を追加
* /api/search/articles にGETで queryパラメータ渡すと記事の全文検索が可能です
* ArticleInfoテーブルに以下のGISを追加しています
* プライマリキー: sync_elasticsearch
* ブロックチェーンへの変更はありません
* 個人情報は収集しないので大丈夫です
* 記事データーとユーザーIDについてはElasticsearchにも保存されます
* ロギングについてはまだ未検討
* ユニットテスト実装済み
* 既存記事データーの同期バッチ
* リアルタイムによるインデックスではなくバッチ処理でインデックスさせる
* batchにも処理を追加しています

Elasticsearchの追加(serverless)

---

.circleci/config.yml
exec_test.py
src/common/settings.py
tests/handlers/me/articles/comments/create/test_me_articles_comments_create.py

CircleCIでビルドが通らなかったので、諸々修正しました。
* CircleCIのvenvを作り直すためにキャッシュ名変更
* テスト時に記事IDで使用するsaltを指定
* 新たに追加されたW605への対応
https://lintlyci.github.io/Flake8Rules/rules/W605.html
なし
* なし
- サーバレス
* 使い方の説明
* バグの場合は再現条件
新たにレポジトリをforkし、環境を作り直したら発生
なし
なし
なし
なし

ALIS-1137: テストが通らなくなってたので修正

---

src/handlers/me/articles/comments/create/me_articles_comments_create.py
tests/handlers/me/articles/comments/create/test_me_articles_comments_create.py

* 自分の書いた記事に対するコメントを行なった場合も通知対象になってしまっていたため、その事象を修正するPR
変更なし
* カスタマー
- サーバレス
* 通知テーブルに対して変更をかける処理の前に、自分の記事に対するコメントかどうかの分岐を入れた
* 自分の記事の場合は以下の２テーブルに対する処理がSKIPされる
* 通知テーブル
* 未読通知管理テーブル

ALIS-1119: Don't create notifications when add comment on own articles.

---

elasticsearch-setup.py
src/common/es_util.py

* なぜこの変更をするのか、
* ユーザー検索部分で部分検索ができないため解消する
* ユーザー検索で自己紹介文も検索対象としてしまうためノイズとなる
* 課題は何か、
* 現在のトークナイザーだと一単語でトークン化されるため部分検索できない
* 自己紹介文の単語も検索対象になってしまう
* N-gramによってトークナイズされるので1文字で検索してもヒットする
* 自己紹介文については検索対象にならない
* 変更していません
* ALIS記事を検索するユーザ（まだリリースしていないため、実ユーザーには影響しません)
* 影響があるのはサーバレス部分だけです
* /search/users のAPI部分のみです
* なにをどう変更したか
* elasticsearch-setup.py を変更し、usersインデックスの設定をN-gramに変更
* src/common/es_util.py を変更し、self_introduction を検索対象から外しました
* elasticsearch-setup.py を変更し、users, articlesのインデックス設定のトークナイザーをデフォルトに設定しました
* elasticsearch-setup.py は ElasticSearch のインデックス設定と作り直すロジックを追加しました
* src/common/es_util.py の match 対象から self_introduction を抜きました
* DBからの取得部分は無いです
* 使い方の説明
* …

user検索部分の変更

---

src/common/settings.py
src/handlers/search/articles/search_articles.py
src/handlers/search/users/search_users.py
tests/handlers/search/articles/test_search_articles.py
tests/handlers/search/users/test_search_users.py

* なぜこの変更をするのか、
* page,queryパラメータのチェックが足りていなかったため
* 課題は何か、
* page, queryパラメータを検証せずにElasticSearchに渡してしまっている
* 不正な値はチェックされElasticSearchに処理させない
* など、この変更に対する概要を記載
* src/common/settings.py にpage, queryの仕様を追記し,jsonschemaでチェックされるようにした
* 変更していません
* 影響を与えるユーザは誰か
* ユーザーへの影響はありません
* セキュリティの対策です
- サーバレス
- /search のAPIでチェック処理が追加されました
* なにをどう変更したか
* src/common/settings.py にpage, query のチェック仕様を追加しました
* src/common/lambda_base.py のvalidate_params でチェックされるようになっています
* 使い方の説明
* 使い方については特に変更ありません
* DBへの変更はありません
* ブロックチェーンへの変更はありません
* 個人情報に関わる部分の修正ではありません
* ログ部分については今回の改修対象外
* 以下のユニットテストを実施しました
* pageパラメーターが範囲外の場合
* queryパラメーターが150文字を超える場合
本件の残TODOはありません
* 特になし

page, quryパラメーターのバリデーション追加

---

src/common/db_util.py
src/common/settings.py
src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py
src/handlers/me/articles/public/republish/me_articles_public_republish.py
tests/common/test_db_util.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py
tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py

* 記事の公開時にTOPICを紐づける処理を追加した
特になし
- フロントエンド
- 公開時（publish と republish）にtopicもパラメータとして投げる必要がある
- プライベートチェーン
* db_utilに指定されたtopicがマスタ登録されているかどうかを検証して、検証に失敗した場合はValidationErrorをraiseするメソッドを作成して、それをリクエスト時に呼ぶようにした。
* DraftPublish と PublicRepublishのupdate時にtopicも一緒にupdateするように修正
* テストの修正

ALIS-1146: Save topic when aritcle is published

---

api-template.yaml
src/handlers/topics/index/topics_index.py
tests/handlers/topics/index/test_topics_index.py

* Topicはname(システム的に管理するname。英字。)とdisplay_name(表示用の文字列。マルチバイトでもなんでも)を分けて管理する想定にする。
* 元々はnameの配列を返却していたが、topicのオブジェクトの配列を返すようにした。
* selectBoxなどでは表示用とvalueに詰めるnameが必要
* 変に整形するよりも全部返してしまった方が、シンプル

Refactor topic index

---

api-template.yaml
src/handlers/me/articles/public/republish/me_articles_public_republish.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py
tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py

* 今は受け取ったパラメータ（クエリパラメータ、パスパラメータ、body）は全てlambda_baseで事前処理としてself.paramsに格納される。
* validateメソッドは上記のself.paramsに対して行うようになっているのだが、一部古いファンクションはクエリパラメータに対して、パスパラメータに対して、のように特定のパラメータに対してバリデーションを行なっている。
* 今回は新規でbodyが増えているのに対してパスパラメータをバリデーションをの対象としていたので、当然topicがパスパラメータになくエラーになってしまっていた。
* そもそもテストケースもpathParameterにtopicを入れていて検知できていなかった
* テストケースの修正も同時に行なった

ALIS-1198: Change args of validate self.params from pathparameters

---

README.md
api-template.yaml
deploy.sh
elasticsearch-setup.py
elasticsearch-template.yaml

* なぜこの変更をするのか、
* ElasticSearchの無停止deployをするため
* 課題は何か、
* ElasticSearchを普通にdeployするとその間検索のAPIが使えなくなる
* ElasticSearchのダウンタイムが無くなる
* 変更していません
* deployに関連するため影響はありません
- サーバレス
* なにをどう変更したか
* cloudformationの定義をElasticSearchだけ分割しました
* ロジックについては手を入れていません
* DBに関係する部分は変更なしです
* 使い方の説明
* `./deploy.sh elasticsearch`でdeployできます
* DBに関して変更はありません
* ブロックチェーンについて影響ありません
* deployスクリプトなので、個人情報関係に影響ありません
* deployなので対象外です
* deployなので対象外です
* stg環境でリハーサル
* 昔のインスタンスは削除してください

split elasticsearch-template

---

database-template.yaml

-  サーバーレスのREADMEに従って環境構築するときに、DBの作成ができないため一時的にDependsOnを追加することによって対応する
- サーバレス
- 開発環境構築時のみ

ALIS-1245: Fix to add DependsOn

---

api-template.yaml

API Doc 化する際に、パラメータ等に不備が無いかを見直したところ下記３箇所に問題があったため修正。
- 新着記事一覧取得時の get に不要なパラメータ（article_id、sort_key）が含まれていたため削除
- 下書き記事 の put に path パラメータが不足していたため追加
- 公開、再公開時処理で type が body  だが schema が定義されていないパラメータが存在したため修正
* API利用ユーザ
- サーバレス

ALIS-1240: Fix api-template

---

src/common/lambda_base.py
tests/common/test_lambda_base.py

* body に渡される値が json 形式の文字列でない場合のエラー処理が間違っている。
本来 status 400 で返すべきだがシステムエラーとして処理されてしまっているため修正。
* 利用ユーザ
- サーバレス
- フロントエンド
・jsonDecode 処理を実行した際に、例外処理を追加し ValidationError(status 400 エラー)を返すように修正
・ また、現在 __init__ 処理にて __get_params を呼び出し jsonDecode を行っているが、__init__ 処理では 値を返すことができないため（status 400エラーを返せないため）、main 処理で 呼び出すように修正。
* 例外発生時に 400 エラーが返ること
* デグレしていないこと（他のテストケースがすべて通ること）
* 今回 __init__  に下記宣言をしているが、これは利用されるクラス変数をひと目で分かるようにするために、宣言を  __init__ に寄せたため。
```
self.params = None
self.headers = None
```

ALIS-1249: Fix 500 status to 400 status

---

api-template.yaml
src/common/es_util.py
src/common/settings.py
src/handlers/search/articles/search_articles.py
tests/handlers/search/articles/test_search_articles.py

* タグによる記事の検索を実現する
* タグの検索は単一タグによる小文字大文字区別なしの一致で行う
特になし
- サーバレス
- フロントエンド
* search_articleに`tag` パラメータを追加
* es_utilの記事検索用メソッドの修正
* tagで検索できるように
* インターフェースを使いやすくした
* テストの追加
* api-templateの修正

ALIS-1254: Enable to search article with tag

---

src/common/es_util.py
tests/handlers/search/articles/test_search_articles.py

* タグでの記事検索を行った場合部分一致になっているため、完全一致となるように修正
* リリース前の為影響なし
- サーバレス
- フロントエンド
* Elasticsearch での query 内で match を使用していたが term を使用し完全一致となるように修正
* 単体テスト記載済み
・半角カナ
・記号（全角）
・記号（半角ハイフン）
・絵文字
・スペースを含んだ文字列
・上記対応により、大文字小文字を区別する仕様となっている
　大文字小文字を区別しないようにする対応は別タスクにて実施

Fix broad match to exact match

---

src/common/es_util.py
tests/handlers/search/articles/test_search_articles.py

* タグで記事を検索する処理に公開日時でソートする処理を追加
* リリース前の為影響なし
- サーバレス
- フロントエンド
* タグ検索を行う場合に published_at の降順でソートするように修正

Fix sort that tag search

---

src/common/settings.py
src/handlers/me/wallet/tip/me_wallet_tip.py

* tip_value に指数表記を対応させる。
* ログイン可能ユーザ
- サーバレス
- フロントエンド
* jsonschema で integer として定義していたが number とすることで指数表記に対応させる。
int型で処理するように型変換を行う（int 型への変換を行うことで小数点以下が落ちるが、そもそも小数点以下は許可していないため、強制的に落とす）

ALIS-1309: Add pattern that exponential notation for tip_value

---

elasticsearch-setup.py
src/common/tag_util.py
src/handlers/me/articles/drafts/publish/handler.py
src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py
src/handlers/me/articles/public/republish/handler.py
src/handlers/me/articles/public/republish/me_articles_public_republish.py
tests/common/test_tag_util.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py
tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py
tests/tests_common/tests_es_util.py

* タグ作成時に大文字小文字を区別していたがそれを区別したくなかった
* 具体的にはタグ作成時に大文字小文字区別せずに検索し、存在したらその表記に合わせてタグの作成を行う
* 例: awsで登録してもAWSがすでに登録されている場合はAWSで登録され、AWSのカウントが上がる
なし
リリースに気をつけないとユーザ影響あり。後述する
- サーバレス
* まず、「大文字小文字を区別する」がDynamoDBだと非常に難しい（方法は全スキャンしかない）
* よってタグ情報を保存するデータストアをESに変更した。
* これにより、タグマスタは不要になる。
* タグ追加時に全てのタグをESに問い合わせて大文字小文字区別せずすでに存在済みかどうかをチェックし、存在してれば存在している形に直して返却させるメソッドを一回通すようにしている
* カウントアップやなかったら作成するロジックも、全て一度上記のメソッドを通して大文字小文字区別しないようにしている
* ElasticSearchは(というかLucene)にセグメントマージという仕組みがあり、一度インデックス情報をバッファメモリにためてある程度まとめてディスクに書き込む（ここで検索可能になる）
* ディスクI/Oを減らす仕組みだが、この間(デフォルトは1sごとにセグメントマージしようとする)は検索対象にならない = この間は文字の大きさ違いのタグが飛んで来た場合はないものとして登録してしまうので、create時には明示的にrefreshをしている
* ここは結構ハックっぽくあまりにもマージが大量に発生しまくると、逆にキューを捌けなくなってrefreshの期間が遅くなることも考えられるのでモニタリングしつつ探っていきたい
* タグテーブルを使わないように修正
* …

ALIS-1265: create tag case insensitive

---

src/handlers/me/articles/public/republish/me_articles_public_republish.py

TagUtil.create_and_count に渡す引数が間違っていたため、修正。

Fix bug that mistake specified es obj

---

database-template.yaml

- サーバーレスのREADMEに従って環境構築するときに、DBの作成ができないため一時的にDependsOnを追加することによって対応する
- サーバレス
- 開発環境構築時のみ

ALIS-1376: Fix to add DependsOn

---

elasticsearch-setup.py

* なぜこの変更をするのか、
* 最新記事一覧で、limit=100&page=100 以上で検索を行うとエラーになるためpage上限値を引き上げる
https://alismedia.atlassian.net/browse/ALIS-1260
* 最新記事一覧閲覧ユーザー
- サーバレス
* なにをどう変更したか
* max_result_windowの値を10000→ 1000000件に変更
[10000件よりアイテム数が多くなるリクエスト](https://gist.github.com/79c6d7b7c32dc8be0be41841c33ce909)を投げてもエラーにならない事を確認

ALIS-1260: ElasticSearchの結果サイズを10000件→1000000件に変更

---

elasticsearch-setup.py
src/common/es_util.py
tests/handlers/search/users/test_search_users.py

* user検索APIにて大文字小文字を区別しないようにする
* ElasticSearchのindex設定を以下の通り変更
* normalizerを追加して、すべて小文字として格納するように追加
* copy_toを使いuser_id,user_display_nameの値をsearch_nameに複製する
* ※ オリジナルのテキストを保存するための措置

ALIS-1248: ユーザ検索時に大文字小文字の区別をしないようように改修する

---

src/common/es_util.py
tests/handlers/search/articles/test_search_articles.py

* タグ検索時に表示順が公開日順になっていないような現象が発見されたため、そのバグ修正
* ElasticSearchで検索する際にソートのキーを `published_at` にしていたが `sort_key` に修正した。
* 今回の問題の原因は `published_at` のmapping定義がfloatになっており、unixtimeが変なところで丸られていたから。である。(なので非常に近いunixtime同士でしか当該事象は発生しない)mapping定義を適切に設定することも対応と言えるが以下の二つの理由からこのPRの対応が適切だと判断している。
* Lambdaによる一覧系の処理はsort_keyでソートしているので合わせた方がシステムの見通しがよくなる
* mappingの変更はESの再デプロイを意味する。コストがかかる。
特になし
- サーバレス
フロントへの影響はない。いままで通りのインターフェースは維持する。
* 単純にsort_keyでdescするようにした。

ALIS-1352: Change sort key when search articles

---

README.md
deploy_api_function.py
requirements_test.txt

api-template.yamlのfunctionを単体でデプロイする機能を作りました。
開発時にソースの更新のたびに`./deploy.sh api`を実行するとかなりの時間を要します。このコマンドを導入することでデプロイにかかる時間が大幅に短縮されるため、開発の生産性が向上します。
なし
なし
APIのバックエンドLambda
- サーバレス
`deploy_api_function.py`をプロジェクトルートに追加。処理の流れとしては以下の通り
- 引数でfunction resource名を受け取る
- それを元にCloudFormationに問い合わせて、function名を取得
- function名とzipファイルから、lambdaのupdate_function_codeメソッドを実行してデプロイ
api-template.yamlの`Resources`配下のServerless::Function名を指定することでデプロイが可能になります。
```
$ ./deploy_api_function.py ArticlesRecent
```
なし
なし
なし
エラー処理して標準出力に吐き出す程度は実施
無し
なし
なし

api-template.yamlのfunction単体をデプロイするスクリプトの追加

---

api-template.yaml
src/common/settings.py
src/handlers/login/line/authorize_request/login_line_authorize_request.py
src/handlers/sign_up/line/authorize_url/handler.py
src/handlers/sign_up/line/authorize_url/sign_up_line_authorize_url.py
tests/handlers/login/line/authorize_request/test_login_line_authorize_request.py
tests/handlers/sign_up/line/authorize_url/test_sign_up_line_authorize_url.py

現状はLINEログイン時に認証画面を毎回挟む仕様となっていた。
それをサインアップ時のみ認証画面を表示し、ログイン時には認証画面を表示しないように変更を加えた。
LINEログインでログインの場合とサインアップの場合で取得するパラメータのスコープを変更した。
上記に伴い、LINEサインアップ用のURLを取得するエンドポイントを追加し、テストを追加した。
- サーバレス
- フロントエンド
なし
なし
あり
あり

ALIS-1613：add line_sign_up_url endpoint, fix line_login_ux

---

src/handlers/me/external_provider_user/create/me_external_provider_user_create.py
tests/handlers/me/external_provider_user/create/test_me_external_provider_user_create.py

@keillera 
外部サービスユーザーがuser_idをPOSTする時のLINE-, Twitter-のPREFIXを許可しないValidationを追加しました。m(_ _)m

add user_id validation

---

src/handlers/cognito_trigger/custommessage/custom_message.py
tests/handlers/cognito_trigger/custommessage/test_custom_message.py

電話番号認証をLINE-, Twitter-のユーザーには許可しない設定を行う変更
Twitter-, LINE-から始まるユーザー名のユーザー
- サーバレス
CustomMessageにバリデーションを追加
なし
追加した
- Twitter-, LINE-から始まるユーザーの場合電話番号認証を行わない
- 通常ユーザーは今まで通り認証可能

ALIS:1633 check line or twitter user

---

src/common/es_util.py
tests/handlers/articles/popular/test_articles_popular.py

* 人気記事に一覧に利用している `article_score` のindexが存在しない場合は現状エラーになるので存在しない場合は空の配列を返すように修正した。
* `article_score` のIndexは他のIndexとは少々異なり、毎度生成し直すという特徴があるため主に開発環境などで消えてしまっていてエラーが発生してしまうケースが散見されていた。（しかもその原因究明にコストがかかる）
* インデックスの存在チェックを行い、存在しない場合は空の配列を返している

ALIS-1538: Return empty list when article score index is not found

---

.circleci/config.yml
src/handlers/articles/comments/index/articles_comments_index.py
tests/handlers/articles/comments/index/test_articles_comments_index.py

* 子コメントのソート順が、仕様と逆順に表示されていたバグの対応
* ALIS利用ユーザ
- サーバレス
- フロントエンド
子コメント取得時のソート順を現在とは逆順に取得するように修正した。
子コメント取得時に逆順ソートとなるように修正を入れている
* ブロックチェーンを参照するか
* ブロックチェーンへのトランザクションが発生するか
bleach のバージョン違いにより、CI でのテストが失敗していたため、 .circleci/config.yml  内でのバージョンを更新しています

ALIS-1962: Fix sort for reply

---

.circleci/config.yml
src/common/settings.py
src/common/text_sanitizer.py
src/handlers/me/articles/drafts/create/me_articles_drafts_create.py
src/handlers/me/articles/drafts/update/me_articles_drafts_update.py
src/handlers/me/articles/public/update/me_articles_public_update.py
tests/common/test_text_sanitizer.py
tests/handlers/me/articles/drafts/create/test_me_article_drafts_create.py
tests/handlers/me/articles/drafts/update/test_me_articles_drafts_update.py
tests/handlers/me/articles/public/update/test_me_articles_public_update.py

ALISエディタのバックエンド（プロトタイプ）の追加
なし
- サーバレス
- フロントエンド
POSTのパラメータとして'version': 200が存在すれば新エディタのデータのPOSTとしてオブジェクトを処理する。
フロントからリクエストされるBlockとして、
Rule
Text
Paragraph
Image
Quote
Heading
Embed
Link
以上のブロックがリクエストされる。
タグを許可するブロック
・Paragraph
　・タグ： ['a', 'b', 'br', 'i', 'p', 'u', 'hr', 'div']
　　・aタグ：
　　　・属性： href / target
　　・b, i, p, u, hr, brタグ：
　　　・属性：なし
　　・divタグ：
　　　・属性：class / style
許可しないブロック
Paragraph 以外全て
ある
箇条書きで書く。可能な限り次のチケットを作る。

ALIS-1909: add alis editor backend

---

api-template.yaml
src/common/settings.py
src/handlers/me/articles/fraud/create/me_articles_fraud_create.py
tests/handlers/me/articles/fraud/create/test_me_articles_fraud_create.py

* 不正記事報告の拡張
特になし
https://alismedia.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=ALIS&modal=detail&selectedIssue=ALIS-1963
* エンドユーザー
- フロントエンド
- 特に影響が著しいので以下に詳細を記載します。
リリース計画的な話でもあるのですが、これをそのままバックエンドだけでリリースしてしまうと
`reason` のバリデーショエラーで既存の通報がのきなみエラーになります。
よって
* ある程度の時間帯はエラーが起きることを許容してフロント改修と一緒にリリースするか
* フロント側でとりあえず `other` などで送りつけるようにしておいて、バックエンドリリースし、そのあとにフロント改修をリリースする
のような対応が必要です。
* パラメータを追加しました。
* 一部JSONSchemaでは実現できないバリデーションは自分で実装しています。
なし
デプロイされたAPIにcallして動作確認済み。
なし

ALIS-1963: Fraud Article Extend

---

src/handlers/cognito_trigger/custommessage/custom_message.py

* 電話番号を他のユーザーと同じものを登録してしまったユーザーのパスワードリセットが出来ないためチェック条件を修正
* バリデーションをする条件にイベントソースが'CustomMessage_ForgotPassword'ではない事を聞くようにしました
以下のケースで本件のバグが再現されます
1. ALIS アカウントを作成（電話番号認証も済ませておく）
2. 再度 ALIS アカウントを作成し、電話番号認証処理の際に、1 と同様の電話番号を設定する
3. 2で作成したユーザーでパスワードリセットができない
* パスワードリセットの正常ケースには既に存在します
箇条書きで書く。可能な限り次のチケットを作る。
* このプルリクはcognito資産の修正なので`./deploy.sh cognito`で反映する必要があります

ALIS-1624: fix cognito validate

---

src/handlers/me/articles/fraud/create/me_articles_fraud_create.py
src/handlers/me/users/fraud/create/me_users_fraud_create.py
tests/handlers/me/articles/fraud/create/test_me_articles_fraud_create.py
tests/handlers/me/users/fraud/create/test_me_users_fraud_create.py

* 不正報告処理で、 free_text が空の場合に例外が発生するバグが存在していたため修正
* DynamoDB が空文字を許可しない仕組みのため発生した問題であるため、空の場合 None を設定するように修正

Fix bug that not allow empty for free_text

---

database-template.yaml

```
./deploy.sh database
```
がリソースIDの重複で落ちるので、UserFraudにした方が良い気がする・・・

fix ResourceId of ScalableTarget

---

api-template.yaml
src/handlers/articles/eyecatch/articles_eyecatch.py
src/handlers/articles/eyecatch/handler.py
tests/handlers/articles/eyecatch/test_articles_eyecatch.py
tests/tests_common/tests_util.py

* アイキャッチ記事の一覧API
特になし
* 記事IDが存在しなかったり(物理削除しない限り起きないが)、下書きに戻されている場合はNoneにして返す
* そもそもアイキャッチのレコードがない場合は、エラーではなくNone３つで返す
* dynamoを直接触るような運用がなければ発生しない

ALIS-2113: Index eyecatch articles

---

api-template.yaml
database-template.yaml
database.yaml
deploy.sh
src/common/settings.py
src/handlers/me/info/first_experiences/update/handler.py
src/handlers/me/info/first_experiences/update/me_info_first_experiences_update.py
src/handlers/me/info/show/me_info_show.py
tests/handlers/me/info/first_experiences/update/test_me_info_first_experiences_update.py
tests/handlers/me/info/show/test_me_info_show.py
tests/tests_common/tests_util.py

* ユーザーが特定の体験を初めて行った瞬間にモーダルを出したい
* そのためにユーザーごとにその体験を行ったかどうかを管理し、その更新をする必要がある
* 上記で追加した情報をユーザー情報取得APIで持ってこれるようにした
* データベースを追加しております
* UserFirstExperience
* ユーザーの体験情報更新API
* 必ず受け取れるキーは一つで、そのキーをTrueにする、という仕立てにしてます。
* キーが想定と異なっていたらバリデーションエラーです。
* meInfoShow
* dict.update を使ってexperience情報を元のdictにupdateしてあげてます。updateは同じキーが被った際に上書きする挙動をしますが、user_idは必ず一致するので問題なしと判断してます。

ALIS-2227: Get user experience info with me info show api

---

.gitignore
api-template.yaml
src/common/settings.py
src/handlers/me/articles/image_upload_url/show/handler.py
src/handlers/me/articles/image_upload_url/show/me_articles_image_upload_url_show.py
tests/handlers/me/articles/image_upload_url/show/test_me_articles_image_upload_url_show.py

* 6MB以上の画像をアップロードする必要があるためLambdaを経由せずに、直接クライアント側にS3を叩いてもらう必要があった。
* そのためS3のpresignedという仕組みを用いて一時的にクライアントサイドからS3の特定バゲットを叩ける情報を返却するエンドポイントを作成した
特になし
- フロントエンド
* presigned postについて 
* https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3.html#generating-presigned-posts
* JSはこんな感じで送ったりしてるところがあるみたいです
* http://imejin.biz/magazine/s3-direct-upload/

ALIS-2257:  Get presigned_post info from AWS

---

src/handlers/me/articles/image_upload_url/show/me_articles_image_upload_url_show.py

test_me_articles_image_upload_url_show.py のテストが
東京リージョン以外だとFailする可能性があるため
s3のクライアントインスタンスを作る際にリージョンを指定するようにした
s3_cli = boto3.client('s3', region_name='ap-northeast-1')
以下のコードによりPre-Signed ULRを生成するが、レスポンスがリージョン事に異なる
([boto3のマニュアル](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html)見る限り、東京リージョンは正しそうなんだけど、オハイオとソウルがバグってる？)
post = s3_cli.generate_presigned_post(
Bucket=bucket,
Key=key,
ExpiresIn=300,
Conditions=[
["content-length-range", content_length, content_length]
]
)
東京リージョンだと存在する `AWSAccessKeyId` や `signature` の名前が変わっていたりする
具体例) https://gist.github.com/yaasita/a1633e1654999f34de797d02f167732e
なんか釈然としない・・・AWS側がバグってるのか？
詳しい人いたら教えて欲しいです。。。

specify tokyo region

---

database-template.yaml

ArticleAlisTokenのDynamoDB On Demandを有効にする
これによりトークン配布処理のキャパシティ不足を解消する
- ArticleAlisTokenテーブル定義に`BillingMode: PAY_PER_REQUEST`を追加
- ArticleAlisTokenテーブル定義のオートスケール設定を削除
* 以下のプルリクエストも同時にマージ下さい
* https://github.com/AlisProject/batch/pull/83

ALIS-2216: enable Dynamodb-On-Demand in ArticleAlisToken

---

api-template.yaml
src/handlers/me/articles/image_upload_url/show/me_articles_image_upload_url_show.py
tests/handlers/me/articles/image_upload_url/show/test_me_articles_image_upload_url_show.py

* generate_presigned_urlを使うようにしました
* https://github.com/AlisProject/serverless-application/pull/219 のPRにもあるのですが署名バージョンによってSignatureなどの返り値のkeyなどが微妙に異なるのでテストのキーも修正しております。

Use generate_presigned_url

---

src/handlers/me/articles/image_upload_url/show/me_articles_image_upload_url_show.py
tests/handlers/me/articles/image_upload_url/show/test_me_articles_image_upload_url_show.py

* image upload の返却値に 表示用のパラメータを追加
- サーバレス
- フロントエンド
* 画像表示のURLをフロントエンド側で作成するには、upload_url をパースする必要があり、処理が煩雑になるためサーバサイド側で生成する方針とした
　

Add show_url for return param

---

api-template.yaml
src/common/db_util.py
src/common/settings.py
src/common/text_sanitizer.py
src/handlers/me/articles/drafts/create/me_articles_drafts_create.py
src/handlers/me/articles/drafts/update/body/handler.py
src/handlers/me/articles/drafts/update/body/me_articles_drafts_update_body.py
src/handlers/me/articles/drafts/update/me_articles_drafts_update.py
src/handlers/me/articles/drafts/update/title/handler.py
src/handlers/me/articles/drafts/update/title/me_articles_drafts_update_title.py
src/handlers/me/articles/public/update/body/handler.py
src/handlers/me/articles/public/update/body/me_articles_public_update_body.py
src/handlers/me/articles/public/update/me_articles_public_update.py
src/handlers/me/articles/public/update/title/handler.py
src/handlers/me/articles/public/update/title/me_articles_public_update_title.py
tests/common/test_db_util.py
tests/common/test_text_sanitizer.py
tests/handlers/me/articles/drafts/update/body/test_me_articles_drafts_update_body.py
tests/handlers/me/articles/drafts/update/title/test_me_articles_drafts_update_title.py
tests/handlers/me/articles/public/update/body/test_me_articles_public_update_body.py
tests/handlers/me/articles/public/update/title/test_me_articles_public_update_title.py

* 新エディタの対応
　・旧バージョンは旧APIのみアクセス可能
　・新バージョンは新API名のみアクセス可能
　・新バージョン用のサニタイジング処理を実装
* ログイン可能ユーザ
- サーバレス
- フロントエンド
（旧バージョンAPI）
・新バージョン用のAPIへの書き込みを制限
（新バージョンAPI）
・title と body を分けて登録する
・新バージョン用にサニタイジング処理を新しく追加

Add process that new version for editor.

---

api-template.yaml
src/handlers/me/articles/drafts/create/me_articles_drafts_create.py
src/handlers/me/articles/drafts/update/body/handler.py
src/handlers/me/articles/drafts/update/body/me_articles_drafts_update_body.py
src/handlers/me/articles/drafts/update/title/handler.py
src/handlers/me/articles/drafts/update/title/me_articles_drafts_update_title.py
src/handlers/me/articles/public/update/body/handler.py
src/handlers/me/articles/public/update/body/me_articles_public_update_body.py
src/handlers/me/articles/public/update/me_articles_public_update.py
src/handlers/me/articles/public/update/title/handler.py
src/handlers/me/articles/public/update/title/me_articles_public_update_title.py

記事のtitleとbodyを保存するフローを分けた
記事を書く全てのユーザー
サーバレス
なし
未追加
箇条書きで書く。可能な限り次のチケットを作る。

[WIP] Separate save article flow

---

src/common/settings.py
tests/common/test_yahoo_utile.py

@keillera 
Yahooログインの際にプロフィールをリクエストする記述を削除しました。
emailとユーザー識別子をリクエストするだけの形に変更しています。

remove yahoo profile request

---

requirements.txt

- elasticsearchのライブラリを本番環境で運用しているバージョン(6.2.0)を指定するよう修正
- CI環境でもこのバージョンを指定して動かしていることを確認

ALIS-2900: CIが落ちていたので修正

---

api-template.yaml
database-template.yaml
database.yaml
deploy.sh
function-template.yaml
src/common/private_chain_util.py
src/common/settings.py
src/handlers/me/wallet/token/send/handler.py
src/handlers/me/wallet/token/send/me_wallet_token_send.py
tests/common/test_private_chain_util.py
tests/handlers/me/wallet/token/send/test_me_wallet_token_send.py
tests/tests_common/tests_util.py

* 出金を行うための API を追加
* TokenSend テーブル追加に伴い環境変数を追加
* ログイン可能ユーザ
- サーバレス
- プライベートチェーン
* 記載済み

ALIS-2677: Add api that token send

---

src/handlers/me/wallet/token/send/me_wallet_token_send.py
tests/handlers/me/wallet/distributed_tokens/show/test_me_wallet_distributed_tokens_show.py
tests/handlers/me/wallet/token/send/test_me_wallet_token_send.py

* approve 実施後の連携完了を待つ処理を削除
（approve、relay ともに nonce パラメータを設定しておりapprove と relay との前後関係を担保できるため、approve 後の連携完了待ち不要）

Fix proc token send

---

api-template.yaml
deploy.sh
requirements.txt
requirements_test.txt
src/common/authlete_util.py
src/common/lambda_base.py
src/common/no_permission_error.py
src/common/settings.py
src/handlers/me/applications/create/handler.py
src/handlers/me/applications/create/me_applications_create.py
src/handlers/me/applications/delete/handler.py
src/handlers/me/applications/delete/me_applications_delete.py
src/handlers/me/applications/index/handler.py
src/handlers/me/applications/index/me_applications_index.py
src/handlers/me/applications/show/handler.py
src/handlers/me/applications/show/me_applications_show.py
src/handlers/me/applications/update/handler.py
src/handlers/me/applications/update/me_applications_update.py
swagger/swagger.yaml
tests/common/test_authlete_util.py
tests/handlers/me/applications/create/test_me_applications_create.py
tests/handlers/me/applications/delete/test_me_applications_delete.py
tests/handlers/me/applications/index/test_me_applications_index.py
tests/handlers/me/applications/show/test_me_applications_show.py
tests/handlers/me/applications/update/test_me_applications_update.py

* クライアントアプリケーション管理用のCRUDエンドポイントを作成
* 単純なCRUDを作成
* index
* show
* create
* update
* delete
* 特にデータベースは使わずにAPI通信のみにしている
* 認可っぽい機構はこっちで担保しないといけなかったので、それぞれのdeveloperが適切なリソースのみにアクセスできるように制御を入れてます。
* エラーハンドリングはAPI通信時にhttpのエラーはもちろん例外として、またAuthleteのAPIの返却値のうち404以外は想定外なのでALISのサーバサイドシステムとしては500でエラー扱いにしてます。
* ほぼmockしてますが書きました。

Create CRUD function of manage application

---

src/common/private_chain_util.py
src/handlers/me/wallet/token/send/me_wallet_token_send.py
tests/common/test_private_chain_util.py

* relay が失敗した際に transaction_hash がDBに保存されない場合があった問題に対応
* transaction 完了確認時、複数の log が存在するケースに対応

ALIS-2992: Fix send flow

---

src/common/exceptions.py
src/common/private_chain_util.py
src/handlers/me/wallet/token/send/me_wallet_token_send.py
tests/common/test_private_chain_util.py
tests/handlers/me/wallet/token/send/test_me_wallet_token_send.py

* 出金額が、残高を超える場合や最大・最小値の範囲に収まっていない場合に、API側で 4xx 系のエラーとして処理するように修正

ALIS-3048: Add validation for token_send

---

database-template.yaml
database.yaml
src/handlers/me/articles/purchase/create/me_articles_purchase_create.py
tests/handlers/me/articles/purchase/create/test_me_articles_purchase_create.py

* PaisStatus のレコード作成時に created_at を付与するように修正
* batch での監視に利用
* 合わせて、batch での監視で PaisStatus のレコードを取得するため、 PaisStatus のDB定義を変更
なし
* ALISチーム（開発者）
- サーバレス
* PaidStatus のレコード作成時に現在時刻を created_at として追加するようにした
* PaidStatus に GSI として status-index を追加

ALIS-3218: Change to add created_at column to PaidStatus table record

---

src/handlers/cognito_trigger/custommessage/custom_message.py
tests/handlers/cognito_trigger/custommessage/test_custom_message.py

* 出金処理のセキュリティ強化のため多要素認証を電話番号を利用して実施するが、現状電話番号をユーザ側から変更可能なため、XSS やパスワード漏洩に対応できない。これに対応するため、電話番号変更を許可しないように修正

ALIS-3234: Add validation that update phone_number.

---

src/handlers/me/allowed_applications/index/me_allowed_applications_index.py
tests/handlers/me/allowed_applications/index/test_me_allowed_applications_index.py

OAuthアプリ一覧で、decriptionも返すように変更
descriptionが無かった場合はnullで返却されます

許可したOAuthアプリ一覧APIでdescriptionも返すようにした

---

function-template.yaml
permission-template.yaml
src/handlers/applications/show/applications_show.py
src/handlers/applications/show/handler.py
swagger/swagger.yaml
tests/handlers/applications/show/test_applications_show.py

* 認可画面表示時に表示するアプリケーション情報を取得API
* Authlete から取得するアプリケーション情報は、client_secret のような公開すべきでない情報が含まれるため、返却する値はホワイトリスト形式で指定している。

ALIS-3380: Add api that get client public info.

---

function-template.yaml

SUCCEEDED_TIP_TABLE_NAMEの指定値が間違っていたので修正

ALIS-3386: Fix to use correct variable

---

api-with-oauth-template.yaml
src/handlers/me/applications/create/me_applications_create.py
src/handlers/me/applications/update/me_applications_update.py
tests/handlers/me/applications/update/test_me_applications_update.py

* API Gateway の設定値を変更（名称を oauth2api に修正、EndpointType を regional に指定）
* アプリケーション作成時、サポート認可種別に「REFREASH_TOKEN」を指定
* アプリケーション更新時処理だが、指定しなかったパラメータは空文字で更新されてしまう仕様だったため事前に現状の情報を取得し、それに上書くような処理に変更
* API Gateway の設定を変更したのは、 Cloudfront 経由でアクセスする方針としたため。名称変更は既存の api と名前が被らないようにするためで、endpoint_type の指定はそもそもデフォルトの edge は裏でcloudfront を叩くしようとなっており、cloudfrontを使用する場合は不要であるため、cloudfrontを通さない regional を設定するように対応した。

ALIS-3484: Fix oauth2api

---

src/handlers/me/wallet/tip/me_wallet_tip.py
tests/handlers/me/wallet/tip/test_me_wallet_tip.py

* 投げ銭の処理にバーンの処理を追加
特になし
*  エンドユーザー
* マージ後は投げ銭量の10%がバーンする
- サーバレス
- フロントエンド
- プライベートチェーン
- バーンのトランザクションを追加している   
* 投げ銭が正常に終了したかを待って、正常に終了したのちバーン処理を追加
* バーン処理自体は有料記事のものを流用。共通化も可能だったが有料記事の方のテスト工数もあるので、一旦記述をただもってきただけにした。
* tipテーブルへの格納は、バーン処理に関わらず行いたいのでfinallyで行う
バーン処理のtransaction hashをtipテーブルに格納
* ブロックチェーンを参照するか
* する
* ブロックチェーンへのトランザクションが発生するか
* バーン処理でトランザクションが発生する

ALIS-2918: Add burn logic in me_wallet_tip

---

src/common/lambda_base.py
tests/common/test_lambda_base.py

* serverless-oauth-api の変更に伴い、lambda_base 側に phone_number_verified と email_verified を True としてパラメータを返す処理を追加

ALIS-3529: Add verified params at lambda_base

---

src/handlers/articles/supporters/index/articles_supporters_index.py
tests/handlers/articles/supporters/index/test_articles_supporters_index.py

* サポーター一覧取得時に、icon_image_urlを必ず指定するように指定している部分を修正
* ユーザーによってはicon_image_urlがない場合もあるので

ALIS-3611: Fix to check user image url

---

src/common/es_util.py
tests/handlers/articles/tip_ranking/test_articles_tip_ranking.py
tests/tests_common/tests_es_util.py

ALIS-3645: Fix to use sort_tip_value

---

src/common/cognito_trigger_base.py
src/common/user_util.py
src/handlers/cognito_trigger/custommessage/custom_message.py
src/handlers/cognito_trigger/postconfirmation/post_confirmation.py
src/handlers/cognito_trigger/preauthentication/pre_authentication.py
src/handlers/cognito_trigger/presignup/pre_signup.py
tests/common/test_cognito_trigger_base.py
tests/common/test_user_util.py
tests/handlers/cognito_trigger/custommessage/test_custom_message.py

* Twitter、LINE 等のサードパーティを利用したアカウントの場合でのパスワード変更を許可しないチェック処理を追加。
* サードパーティを利用したアカウントを保持しているユーザ
- サーバレス
- フロントエンド
Cognito Trigger で利用するための基底クラス（CognitoTriggerBase）を追加しています。
これは現状利用している LambdaBase での例外処理が、Cognito Trigger 利用時では問題があったため。
（問題）
LambdaBase では API を想定して作っており例外を発生した場合は、例外を握りつぶし { 'status': 500, 'message': 'hoge'} のような json でメッセージを返却するが、Cognito Trigger の場合は例外 Exception('hoge') のまま握りつぶさずに終了させないと例外時のメッセージをフロントに返却できない。
握りつぶさないことで下記のような json でフロントに返却することができる。
```
{"__type":"UserLambdaValidationException","message":"CustomMessage failed with error hoge."}
```
この CogniotTriggerBase への変更は影響範囲が広いので、今回修正対象（custom_message）にのみ反映しています。
* ユーザIDから、サードパティアカウントかを判定し、サードパーティアカウントの場合は例外を発生させ処理を中断させている
基底クラス含め、テストコード実装済み

ALIS-3200: Add validate for custom message

---

cloudfront-template.yaml

* Behavior の設定（/api/wallet/bridge_information ）が足りていなかったため追加
* 該当 tempate を用いてデプロイし、意図する Behavior が追加されることを確認済み

ALIS-3734: Add behavior of bridge_information for cloudfront.

---

api-template.yaml
database-template.yaml
database.yaml
deploy.sh
function02-template.yaml
permission-template.yaml
src/common/db_util.py
src/common/settings.py
src/handlers/me/articles/content_edit_histories/index/handler.py
src/handlers/me/articles/content_edit_histories/index/me_articles_content_edit_histories_index.py
src/handlers/me/articles/drafts/body/update/me_articles_drafts_body_update.py
src/handlers/me/articles/drafts/show/me_articles_drafts_show.py
src/handlers/me/articles/public/body/update/me_articles_public_body_update.py
src/handlers/me/articles/public/edit/me_articles_public_edit.py
swagger/swagger.yaml
tests/common/test_db_util.py
tests/handlers/me/articles/content_edit_histories/index/test_me_articles_content_edit_histories_index.py
tests/handlers/me/articles/drafts/body/update/test_me_articles_drafts_body_update.py
tests/handlers/me/articles/drafts/show/test_me_articles_drafts_show.py
tests/handlers/me/articles/public/body/update/test_me_articles_public_body_update.py
tests/handlers/me/articles/public/edit/test_me_articles_public_edit.py
tests/tests_common/tests_util.py

編集内容の履歴を取得できる機能を追加（100世代）
API
（改修）
- 下書き記事_本文更新：本文を履歴にも保存する
- 編集記事_本文更新：本文を履歴に保存する
- 下書き記事取得：バージョンを指定した場合、指定バージョンで本文を上書く
- 編集記事取得：バージョンを指定した場合、指定バージョンで本文を上書く
（新規）
履歴バージョン情報一覧取得
- 該当記事の履歴バージョン一覧を取得
テーブル追加に伴い
* 変更した場合は以下の作業を行う
- サーバレス
- フロントエンド   
* ArticleContentEditHistory テーブルを追加
* 観点: 下記2点のために、article_id-sort_key-index を追加しているが、容量削減のため body は 射影に含めていない
- 最新のバージョンを取得
- 履歴バージョン情報一覧取得
* 実装済み

ALIS-3743: Add edit history

---

requirements.txt
src/common/crypto_util.py
src/common/rsa_algorithm.py
src/common/yahoo_util.py
tests/handlers/login/twitter/index/test_login_twitter_index.py

- pycryptoとweb3.pyがバッティングするので対応
- web3.pyではpycryptoの後継であるpycryptodomeを使用していて、両方とも同じ名前空間を使用している事が原因
- pycryptoの使用を廃止し、pycryptodomeに寄せた
- しかし、pyjwtの仕様上、一部うまく寄せられない部分があったので、そこは独自のクラスを噛ませて差分を吸収した
* No
* 影響を与えるユーザは誰か
- なし
- サーバレス
* なし
* なにをどう変更したか
- pycryptoの使用を廃止し、pycryptodomeに寄せた
- それにともないコードを微修正
- 変わりなし
- なし
- No
- 無い
- 無い
- 無い
* なし
* アラームが必要か
* 不要
* 修正済
- FB
- Yahoo
- Line
- Twitter
- 新規登録したあと、一瞬赤いローダが表示される。しかしこれはステージングで元々発生していた現象の模様。
- 別途要調査
- OAuthが絡む箇所で環境構築負荷が高いためステージングにデプロイされるよう、AlisProjectのアカウントでブランチを切り作業している

change pycrypto to pycryptodome

---

.circleci/config.yml
package.json

* なぜこの変更をするのか、
- serverless-applicationをGitHub Flowへ変更
* 課題は何か、
- 工数削減
* No
- サーバレス
* ブランチ戦略の変更
* なにをどう変更したか
- GitHubのデフォルトブランチをmasterに
- CI構成を変更
以下のようなCIワークフローとした。
- なし
* なし
- No
- 無い
- 無い
- 無い
* なし
- 3つのワークフローともに問題なし
* ついでにalarmsのデプロイ処理も追加しました。
PRをマージ後、そのままdevelopをmasterにマージしてステージング環境へ反映されることをご確認ください。本番環境へのビルドは放置でおｋです。

change to GitHub Flow

---

apialarms-template.yaml

* なぜこの変更をするのか、
- ステージング環境でもアラートを飛ぶようにするため
* 課題は何か、
- ステージング環境で拾えるエラーを適切に拾えていない
- ステージング環境のエラーがSlack通知されるようになる
- アラームのみ
* 本番への `alarms:SNSTopicAlarmToSlack` は既に構築済
- https://github.com/AlisProject/alarms/blob/master/serverless.yml#L863
- マージしていただけたらデプロイはこちらで行います

fix SNS for alarms

---

src/common/es_util.py
tests/handlers/articles/recent/test_articles_recent.py
tests/tests_common/tests_es_util.py

* 新記事一覧取得の際に、不要なパラメータ（body）も取得していたため、取得対象から除外した。
* ElasticSearch から取得する際、取得対象の項目を指定するように修正。

ALIS-4028: Fix bug that return body.

---

src/handlers/me/applications/create/me_applications_create.py
tests/handlers/me/applications/create/test_me_applications_create.py

* Authlete API がメジャーバージョンアップを行うため、それに伴う対応
https://kb.authlete.com/ja/s/authlete-2-dot-0
* tokenAuthMethod の値を適切に設定する必要があるため、設定パラメータを追加

ALIS-4775: Add parameter of tokenAuthMethod to oauth application.

---

src/common/db_util.py
src/handlers/me/articles/comments/create/me_articles_comments_create.py
src/handlers/me/articles/comments/reply/me_articles_comments_reply.py
src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py
src/handlers/me/articles/drafts/publish_with_header/me_articles_drafts_publish_with_header.py
src/handlers/me/articles/public/republish/me_articles_public_republish.py
src/handlers/me/articles/public/republish_with_header/me_articles_public_republish_with_header.py
tests/common/test_db_util.py
tests/handlers/me/articles/comments/create/test_me_articles_comments_create.py
tests/handlers/me/articles/comments/reply/test_me_articles_comments_reply.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py
tests/handlers/me/articles/drafts/publish_with_header/test_me_articles_drafts_publish_with_header.py
tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py
tests/handlers/me/articles/public/republish_with_header/test_me_articles_public_republish_with_header.py

* 判定対象ユーザに対して、記事の投稿とコメントの書き込みを制限する処理を追加
* 制限対象ユーザ
- サーバレス
- フロントエンド

ALIS-4986: 書き込み制限処理を追加

---

src/common/es_util.py
src/handlers/articles/popular/articles_popular.py
src/handlers/articles/recent/articles_recent.py
src/handlers/articles/tip_ranking/articles_tip_ranking.py
src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py
src/handlers/me/articles/drafts/publish_with_header/me_articles_drafts_publish_with_header.py
src/handlers/me/articles/public/republish/me_articles_public_republish.py
src/handlers/me/articles/public/republish_with_header/me_articles_public_republish_with_header.py
tests/handlers/articles/popular/test_articles_popular.py
tests/handlers/articles/recent/test_articles_recent.py
tests/handlers/articles/tip_ranking/test_articles_tip_ranking.py
tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py
tests/handlers/me/articles/drafts/publish_with_header/test_me_articles_drafts_publish_with_header.py
tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py
tests/handlers/me/articles/public/republish_with_header/test_me_articles_public_republish_with_header.py

ブラックリスト該当ユーザに対して下記の対応を実施
- 一覧表示の制限を追加
- 投稿の制限を削除
* 一覧表示の制限については主に es_util.py にて行っていますが、テストは test_es_util.py ではなく呼び出し側で行っています。これはElasticsearch についてのテストは index を作ったりと複雑さがあり、呼び出し側で合わせて動作確認しているためです（既存を踏襲）。

ALIS-5052: 一覧表示の制限を追加

---

src/common/settings.py
src/common/text_sanitizer.py
tests/common/test_text_sanitizer.py

* `alis-editor` に `code-block` プラグインを追加することに伴って `<pre>` と `<code class="language-xxx">` のhtmlタグを許可する必要がある。
* `alis-editor` pull request
[CKEditor5のバージョンアップ（v16.0.0）とcode-blockプラグインの追加](https://github.com/AlisProject/alis-editor/pull/92)
* 全ユーザー
- サーバレス
- フロントエンド
- エディター
* `html_allowed_tags_v2` に `pre` と `code` を追加
* `TextSanitizer.allow_code_v2` で `language-xxx` フォーマットの `class` を許可
* `test_sanitize_article_body_with_code_unauthorized_class` でイリーガルな `class` をテスト
* `test_sanitize_article_body_v2` に `<pre>` と `<code>` エレメントを追記してテスト
* ローカルにテスト環境の構築ができてないので、実際にテストができていない。

エディターのコードブロック追加に伴って<pre>と<code>タグを許可

---

src/handlers/authorizer/authorizer.py
tests/handlers/authorizer/test_authorizer.py

* oauth2 の authorizer 処理で、アクセストークンが不正だった場合に lambda が例外が発生していた。アクセストークンはユーザが指定するパラメータのため、例外ではなくアクセス拒否とするように修正

ALIS-5483: Modify UNAUTHORIZED pattern for authorizer

---

src/handlers/authorizer/authorizer.py
tests/handlers/authorizer/test_authorizer.py

* 結合テストにて、UNAUTHORIZED の場合 subject が空であることがわかった。後続処理で subject 値を使うことは無いため、定数を利用する方法で対応

ALIS-5483: Fix bug that key error for subject.

---

src/common/authlete_util.py
tests/common/test_authlete_util.py
tests/handlers/me/applications/create/test_me_applications_create.py
tests/handlers/me/applications/update/test_me_applications_update.py

* アプリケーション登録にて、redirect-url の指定が不正だった場合に 500 エラーが発生してしまうケースが存在した。正しくは 400 を返すのが正しいため、例外処理を修正
* 元々 redirect-url 自体は jsonschema で uri フォーマットであることのチェックをしていたが、Authlete に登録・更新する場合はそれだけでは不足していることが今回の事象で発覚した。このため Authlete 登録・更新時にレスポンスの値を確認する処理を追加し、該当処理で例外が発生しないように修正した。
* 修正箇所は authlete_util.py のみだが、メッセージの確認含め詳細なテストも実施したかったため、呼び出し側である登録・更新についてもテストケースを追加した
* test_me_applications_create.py
* test_me_applications_update.py
- 開発環境にて動作確認済みです。
- 内容を確認し、問題なければマージしてください。

ALIS-5528: Add a validation process to authlete util.

---

src/common/lambda_base.py
src/common/user_util.py
tests/common/test_lambda_base.py
tests/common/test_user_util.py

* カストディ対応によって、OAuth 対応API で private_eth_address が必要になるケースがあったため、OAuth 経由でも private_eth_address を取得できるように回収   
* OAuth 経由でアクセスがあった場合、該当ユーザに紐づく private_eth_address をDBより取得するように修正

ALIS-5551: Add parameter private_eth_address for OAuth access.

---

.circleci/config.yml

* なぜこの変更をするのか、
- DockerHubが11月からpull数に制限を課すので、それを回避するため
* 課題は何か、
- 制限のせいでCIが落ちるかも
- ひとまず `200pulls/6h`までは制限が回避される
- CircleCIのContextに該当情報を追加済み
* 影響を与えるユーザは誰か
- なし
- CI/CD
- 本ページを共有
* なにをどう変更したか
- DockerをDocker Hubからpullする処理に認証を追加
* 使い方の説明
- いつもと変わらず
- 内容を確認し、問題なければマージしてください。
- ステージング環境のビルドが問題なく完了することを確認してください
- 基本的に本番環境もステージング環境も処理は変わらないはずなので、ステージング環境のみの確認でOKです。

add docker hub auth to CircleCI
