AlisProject/serverless-application

.circleci/config.yml, requirements.txt, requirements_test.txt
・テスト関連のライブラリ管理は別ファイルにて実施するように修正（requrements_test.txt）
・pycodestyle にて静的解析を実施（pycodestyle は 旧pep8）
=> Add checkstyle for python code

.gitignore, database.yaml, src/handlers/article_alis_tokens/show/article_alis_token_show.py, src/handlers/article_alis_tokens/show/handler.py, template.yaml, tests/handlers/article_alis_tokens/show/test_show.py
* Create Table. ArticleEvaluatedManage and ArticleAlisToken
* Create Function for getting number of alis token
* Create endpoint with API Gateway
=> ALIS-107: Create ArticleAlisToken Show Api

database.yaml, src/common/lambda_base.py, src/common/settings.py, src/handlers/articles/likes/post/articles_likes_post.py, src/handlers/articles/likes/post/handler.py, template.yaml, tests/handlers/articles/likes/post/test_articles_likes_post.py
* Create add like API
* Fixed codeuri value
=> ALIS-296: Create add like API

src/handlers/article_info/recent/article_info_recent.py, tests/handlers/article_contents/show/test_article_content_show.py, tests/handlers/article_info/recent/test_article_info_recent.py
* Change name of status.(`published` to `public`)
=> Change name of status

.gitignore, README.md, make_template.py, requirements.txt, src/handlers/cognito_trigger/handler.py, template.yaml, template.yaml.tpl
change the verification code to link
=> change sign up flow

template.yaml.tpl
fix upload error
```
Parameter CodeUri of resource ArticlesRecent refers to a file or folder that does not exist /home/serverless/serverless-application/deploy/article_info_recent.zip
Parameter CodeUri of resource ArticlesShow refers to a file or folder that does not exist /home/serverless/serverless-application/deploy/article_contents_show.zip
Parameter CodeUri of resource ArticlesAlisTokensShow refers to a file or folder that does not exist /home/serverless/serverless-application/deploy/article_alis_tokens_show.zip
```
=> fix CodeUri parameter

exec_test.py, src/common/db_util.py, src/handlers/articles/likes/get/articles_likes_get.py, src/handlers/articles/likes/get/handler.py, src/handlers/articles/likes/post/articles_likes_post.py, tests/common/test_db_util.py, tests/handlers/articles/likes/get/test_articles_likes_get.py, tests/tests_common/tests_util.py
* create api for likes count.
* make DBUtil
* make TestsUtil
=> ALIS-108: Add likes count api

database.yaml, src/common/settings.py, src/handlers/users/articles/public/handler.py, src/handlers/users/articles/public/users_articles_public.py, template.yaml.tpl, tests/handlers/users/articles/public/test_users_articles_public.py
* Create index(user_id and sort_key)
* Create function for getting list of public articles.
* Add tests.
=> ALIS-205: Create get public article api

.circleci/config.yml, Dockerfile, README.md, make_deploy_zip.py, make_template.py, requirements_test.txt, template.yaml.tpl
* Add deploy process to circleci.
* Update README.md
=> Add deploy process to circleci

README.md, make_template.py, template.yaml.tpl
=> change API_NAME to AWS::StackName

database.yaml, src/handlers/cognito_trigger/postconfirmation/handler.py, src/handlers/cognito_trigger/postconfirmation/post_confirmation.py, template.yaml.tpl, tests/handlers/cognito_trigger/postconfirmation/test_post_confirmation.py, tests/tests_common/tests_util.py
add this test and separate class files
=> ALIS-341: add test cognito trigger of postconfirmation

.circleci/config.yml, tests/common/test_db_util.py, tests/common/test_lambda_base.py, tests/handlers/articles/alis_tokens/show/test_articles_alis_tokens_show.py, tests/handlers/articles/likes/show/test_articles_likes_show.py, tests/handlers/articles/recent/test_articles_recent.py, tests/handlers/articles/show/test_articles_show.py, tests/handlers/cognito_trigger/postconfirmation/test_post_confirmation.py, tests/handlers/me/articles/drafts/create/test_me_article_drafts_create.py, tests/handlers/me/articles/drafts/show/test_me_articles_drafts_show.py, tests/handlers/me/articles/drafts/update/test_me_articles_drafts_update.py, tests/handlers/me/articles/images/create/test_me_articles_images_create.py, tests/handlers/me/articles/like/create/test_me_articles_like_create.py, tests/handlers/me/articles/like/show/test_me_articles_like_show.py, tests/handlers/me/info/update/test_me_info_update.py, tests/handlers/users/articles/public/test_users_articles_public.py, tests/tests_common/tests_util.py
・Add mode that use Dynamodb of AWS Service (not localstack)
　But this mode take long time(10min over). So not available in CircleCI 
・Modify container to use DynamoDB of AWS.
https://docs.aws.amazon.com/ja_jp/amazondynamodb/latest/developerguide/DynamoDBLocal.html
=> Modify container to use DynamoDB of AWS.

src/handlers/cognito_trigger/postconfirmation/post_confirmation.py, tests/handlers/cognito_trigger/postconfirmation/test_post_confirmation.py
=> ALIS-341: add "user_display_name" to the Users table

template.yaml.tpl
=> do not require for phone number

.circleci/config.yml, README.md, template.yaml.tpl
・Mod password policy
・Add requestTemplates and authorizer for restapi
・Add s3-bucket option to cloudfront deploy command.  Becouse template.yaml is over 51200 byte.
・Add auth option to api method.
=> Add requestTemplates and authorizer for restapi

database.yaml, src/handlers/me/articles/drafts/publish/handler.py, src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py, template.yaml.tpl, tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py, tests/tests_common/tests_util.py
* Publish draft article.
* Delete article_content_edit if it exists.
* Create article history when article is published.
=> ALIS-119: Publish draft article

src/common/settings.py, src/handlers/me/info/icon/create/handler.py, src/handlers/me/info/icon/create/me_info_icon_create.py, template.yaml.tpl, tests/handlers/me/articles/images/create/test_me_articles_images_create.py, tests/handlers/me/info/icon/create/test_me_info_icon_create.py, tests/tests_common/tests_util.py
* Add api that upload user icon
* Refactor tests_util.py
=> Add api that upload user icon

src/handlers/me/articles/public/edit/handler.py, src/handlers/me/articles/public/edit/me_articles_public_edit.py, template.yaml.tpl, tests/handlers/me/articles/public/edit/test_me_articles_public_edit.py
=> ALIS-121: Create article edit api

src/handlers/users/info/show/handler.py, src/handlers/users/info/show/users_info_show.py, template.yaml.tpl, tests/handlers/users/info/show/test_users_info_show.py
* Add API that show user info. 
* Fix a bug that not defined security item in me/info/icon
=> Add API that show user info.

src/handlers/me/articles/public/show/handler.py, src/handlers/me/articles/public/show/me_articles_public_show.py, template.yaml.tpl, tests/handlers/me/articles/public/show/test_me_articles_public_show.py
* Create api for getting an article of login user
* Rename StorieContent to ArticleContent
=> ALIS-120: Create api for getting an article of login user

src/handlers/me/articles/public/edit/handler.py
=> ALIS-381: Fix a class name and variables in handler.py

template.yaml.tpl
* Change http method to get from put.
=> Fix http method

template.yaml.tpl
* stage nameをdev => apiに変更
* cloudfrontをapi-gateway前に設置
=> ALIS-355: add cloudfront in front of API Gateway

src/handlers/me/articles/public/unpublish/handler.py, src/handlers/me/articles/public/unpublish/me_articles_public_unpublish.py, template.yaml.tpl, tests/handlers/me/articles/public/unpublish/test_me_articles_public_unpublish.py
* Create api for unpublishing public articles
=> ALIS-123: Create api for unpublishing public articles

src/handlers/me/articles/public/update/handler.py, src/handlers/me/articles/public/update/me_articles_public_update.py, template.yaml.tpl, tests/handlers/me/articles/public/update/test_me_articles_public_update.py
* Create public article's update api.
=> ALIS-122: Create public article's update api

src/handlers/me/articles/public/republish/handler.py, src/handlers/me/articles/public/republish/me_articles_public_republish.py, template.yaml.tpl, tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py
* Create api to publish edited contents
=> ALIS-209: Create api to publish edited contents

database.yaml, src/common/settings.py, src/handlers/articles/alis_tokens/show/articles_alis_tokens_show.py, src/handlers/articles/popular/articles_popular.py, src/handlers/articles/popular/handler.py, template.yaml.tpl, tests/handlers/articles/alis_tokens/show/test_articles_alis_tokens_show.py, tests/handlers/articles/popular/test_articles_popular.py, tests/tests_common/tests_util.py
* Create index popular articles API
=> ALIS-104: Create index popular articles API

README.md, database.yaml, make_template.py, src/handlers/cognito_trigger/postconfirmation/post_confirmation.py, src/handlers/cognito_trigger/presignup/pre_signup.py, template.yaml.tpl, tests/handlers/cognito_trigger/postconfirmation/test_post_confirmation.py, tests/handlers/cognito_trigger/presignup/test_pre_signup.py, tests/tests_common/tests_util.py
* BetaUsersテーブルを追加
* BETA_MODE_FLAG=1の時にBetaUsersテーブルにメールアドレスが無い場合はSignUp不可
* Verifyした段階で、BetaUsersテーブルのusedフラグを立てる
=> ALIS-341: add beta mode

src/handlers/articles/alis_tokens/show/articles_alis_tokens_show.py, tests/handlers/articles/alis_tokens/show/test_articles_alis_tokens_show.py
* Return 200 when article_evaluated_manage is not found.
* Return 200 when article_alis_token is not found.
=> Fix bug with no article evalueted manager

src/common/settings.py, src/handlers/cognito_trigger/custommessage/custom_message.py, src/handlers/cognito_trigger/custommessage/handler.py, template.yaml.tpl, tests/handlers/cognito_trigger/custommessage/test_custom_message.py
以下チェックを追加
* 日本の電話番号かチェック
* 既に使われている電話番号じゃないかチェック
=> ALIS-376: add phone number validation

src/handlers/cognito_trigger/custommessage/custom_message.py, tests/handlers/cognito_trigger/custommessage/test_custom_message.py
パスワードリセット時のメッセージを変更
（パスワードリセット時は確認リンクではなく確認コードなので）
=> add password reset message

src/handlers/cognito_trigger/presignup/pre_signup.py, tests/handlers/cognito_trigger/presignup/test_pre_signup.py
email addressの重複チェック追加
(テスト時だけtriggerSourceの値を空にして、cognitoとの通信部分は飛ばしてます)
=> ALIS-376: check duplicate email address

database-template.yaml
* テンプレートからDBの作成に失敗していたため修正
* 開発者
- サーバレス
* タイポ箇所を修正
=> Fix typo for datebase-template

.circleci/config.yml, packaging.sh
細かい修正
- batchで発生していたvender-package問題に対処
- CI環境にALIS_APP_IDが含まれる場合にのみデプロイ処理を実行するよう修正
=> remove vendor-package directory in packaging script

.circleci/config.yml, .gitignore, README.md, exec_test.py, tests/tests_common/tests_util.py
* ローカルの単体テストの実行やCI上の実行が非常に遅く、開発効率を下げていたためその打ち手として実施
環境変数の追加、変更はない
localstackの調査
https://alismedia.atlassian.net/wiki/spaces/DEV/pages/10616964
docker hub
https://hub.docker.com/r/alismedia/dynamodb-local/
git hub
https://github.com/AlisProject/dynamodb-local
なし
* 詳細はコメントに書いていきますが大まかには以下です。
* localstack -> dynamodb-local
* exec_testのリファクタ
* 引数でファイルを指定できるようにした
* greenの実行方法を変えた
* test_utilのリファクタ
* dynamoの削除処理のチューニング
* テストデータ挿入処理のリューニング
* READMEに記載
=> Tuning local test

api-template.yaml, database-template.yaml, database.yaml, deploy.sh, src/common/settings.py, src/handlers/topics/index/handler.py, src/handlers/topics/index/topics_index.py, tests/handlers/topics/index/test_topics_index.py, tests/tests_common/tests_util.py
https://alismedia.atlassian.net/wiki/spaces/DEV/pages/16580770/TOPIC#TOPIC%E6%A9%9F%E8%83%BD%E9%96%8B%E7%99%BA%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6-TopicIndex
* 変更したとしたらどのような変更か
* 変更した場合は以下の作業を行う
* https://github.com/AlisProject/environment/pull/11
* さくっとstagingに手動でDBとSSMを追加しようと思ったものの、現状運用としてCFnを使ってるとあとあと面倒になりそうなのでその辺をお聞きしてから作業します。
- サーバレス
- フロントエンド
* 単純にシステムマスタとして登録したトピックの一覧を返すAPIを作成
* あとで順序をいじりたくなってくる想定で、固定キーをハッシュキー、orderをレンジーとしたGSIを作ってる。（冗長だがDynamoだとこれしかやりようがない）
=> ALIS-1145: Create topic index

README.md
=> ALIS-1250: 環境整備

.gitignore, README.md, add_master_data.sh, misc/topics.json
=> ALIS-1250:環境改善

api-template.yaml
* Functionの指定が間違っていたため修正
* Function定義のkeyが単数系になっていたため修正
=> Fix template

src/handlers/search/tags/search_tags.py, tests/handlers/search/tags/test_search_tags.py
* 渡されたパラメータに対して、integer への変換処理が不足していたため、追加
=> Fix bug that don't convert to integer

src/handlers/me/articles/public/republish/handler.py
=> Fix bug that not specified es object

database.yaml
* 詳細は
* https://alismedia.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=ALIS&modal=detail&selectedIssue=ALIS-1301
* https://github.com/AlisProject/batch/blob/develop/database.yaml と差分が出ないように修正した。
=> Fix database.yaml

deploy_api_function.py
修正して以下のコマンドで問題ないことを確認済み
```
$ pycodestyle src tests ./*.py
$ pyflakes src tests ./*.py
```
=> #185 で発生したスタイルチェックの修正

src/handlers/cognito_trigger/preauthentication/pre_authentication.py, tests/handlers/cognito_trigger/preauthentication/test_pre_authentication.py
APIでCognitoの認証が行うことができるように修正。
変更していない
- サーバレス
テストを修正した
=> ALIS-1646：Fix pre authentication

database-template.yaml
@keillera 
database-templateのNotificationの定義が間違っているため修正を行なった。
- サーバレス
Notificationのデータベース定義を正しく修正
なし
=> ALIS-1626：fix notification databse-template

.circleci/config.yml, src/handlers/cognito_trigger/custommessage/custom_message.py
* SMSメッセージの文言を変更
SMS認証のメッセージを以下のように変更しました
```
{user}さんの検証コードは {code} です。
```
```
ALISです。
{user}さんの検証コードは {code} です。
```
* CircleCIのキャッシュが狂ってるせいでテストがこけてますが正常です
=> ALIS-1433: sms message

api-template.yaml, database-template.yaml, database.yaml, deploy.sh
=> ALIS-2112: Add table ScreenedArticle

api-template.yaml, deploy.sh
TokenDistributionのTableNameの定義が抜けてたので足しております。
=> Add environment variable of TokenDistribution

src/handlers/cognito_trigger/custommessage/custom_message.py, tests/handlers/cognito_trigger/custommessage/test_custom_message.py
=> Update message for email

deploy_api.sh
@keillera 
deploy_api.shへの追加漏れです(自身のCIではキャッシュでよしなに回っていたようです。)
=> add AlisAppId to deploy_api.sh

database.yaml
* 公式からのアナウンス機能追加のため、notification テーブルに index を追加
=> Add index for notification

api-template.yaml, function-template.yaml, permission-template.yaml, src/common/db_util.py, src/handlers/articles/price/show/articles_price_show.py, src/handlers/articles/price/show/handler.py, tests/common/test_db_util.py, tests/handlers/articles/price/show/test_articles_price_show.py
* 記事の価格を取得するAPIを追加
CloudFrontの設定を更新する
=> ALIS-2597: Add get price API

src/handlers/articles/show/articles_show.py, tests/handlers/articles/show/test_articles_show.py
=> ALIS-2588: Update article show API for paid article

src/handlers/me/articles/public/show/me_articles_public_show.py, tests/handlers/me/articles/public/show/test_me_articles_public_show.py
=> ALIS-2593: Update me articles public show for paid article

function-template.yaml
=> ALIS-2631: Fix function-template

api-template.yaml, function-template.yaml, permission-template.yaml, src/handlers/me/articles/purchased/show/handler.py, src/handlers/me/articles/purchased/show/me_articles_purchased_show.py, tests/handlers/me/articles/purchased/show/test_me_articles_purchased_show.py
=> ALIS-2591: Add MeArticlesPurchasedShow API

tests/handlers/articles/popular/test_articles_popular.py, tests/handlers/articles/recent/test_articles_recent.py, tests/handlers/me/articles/public/index/test_me_articles_public_index.py, tests/handlers/users/articles/public/test_users_articles_public.py
=> ALIS-2594: Update get articles tests

database-template.yaml, database.yaml
=> ALIS-2638: Remove useless definition

cognito-template.yaml, database-template.yaml
- ↓と同時PR
-https://github.com/AlisProject/environment/pull/29 
* なぜこの変更をするのか、
- 環境構築を行う途中、改善点がいくつか存在したためついてに改善を行う。
* 課題は何か、
- 環境構築手順に改善点が存在した
- DynamoDBのスケーリングがすべてオンデマンドとなる
- Cognitoの構築でひと手間減る
- **この修正では本番環境には一切影響を及ぼさない。**
- DynamoDBもCognitoもすでにCloudFormationの管理を外れているから。あくまで環境構築の改善
* No
* 今後、環境構築をする開発者
- サーバレス
* DynamoDBのスケーリングをすべてオンデマンドに
* CognitoのSNS外部認証用の設定をコード化
* いつもと同じ
- 本番環境への影響無し
* 無し
* 無し
- API以降の構築は別タスクとして切り出した
- https://alismedia.atlassian.net/browse/ALIS-2623
=> ALIS-2603: 環境整理

permission-template.yaml
* 購入した記事の記事ID一覧を取得するAPIのpermission-templateを追記
=> ALIS-2645: Fix to add permission template

api-template.yaml
=> ALIS-2720: Fix cognito auth at MeArticlesPurchasedArticleIdsIndex

src/handlers/me/articles/public/edit/me_articles_public_edit.py, tests/handlers/me/articles/public/edit/test_me_articles_public_edit.py
* 公開した有料記事の編集情報を取得するAPIを修正
* paid_body の存在を考慮していなかったので追加した
=> ALIS-2787: Fix MeArticlesPublicEdit API

src/handlers/me/articles/purchased/show/me_articles_purchased_show.py, tests/handlers/me/articles/purchased/show/test_me_articles_purchased_show.py
* 有料記事の取得APIを修正
* 取得する記事が購入済みで、無料になっていた場合でも取得できるようにした
=> ALIS-2800: Fix MeArticlesPurchasedShow API

src/handlers/me/articles/drafts/show/me_articles_drafts_show.py, tests/handlers/me/articles/drafts/show/test_me_articles_drafts_show.py
* 有料記事を下書きに戻すと有料部分の本文が消えないように修正
=> ALIS-2862: Fix MeArticlesDraftsShow API

.gitignore
開発環境でDynamoDB Localを使用する際に関連ファイルが邪魔になるため修正。
=> add DynamoDBLocal to .gitignore

src/common/db_util.py, src/common/text_sanitizer.py, src/handlers/me/articles/drafts/publish_with_header/me_articles_drafts_publish_with_header.py, src/handlers/me/articles/public/republish_with_header/me_articles_public_republish_with_header.py, tests/common/test_db_util.py, tests/common/test_text_sanitizer.py, tests/handlers/me/articles/drafts/publish_with_header/test_me_articles_drafts_publish_with_header.py, tests/handlers/me/articles/public/republish_with_header/test_me_articles_public_republish_with_header.py
* 公開処理時にチェック処理を追加
・タイトル、本文が設定されていること
・eye_catch_url をドメインと同様のものが設定されていること
=> Add validate process to publish method

api-template.yaml, function-template.yaml, permission-template.yaml, src/handlers/wallet/bridge_information/show/handler.py, src/handlers/wallet/bridge_information/show/wallet_bridge_information_show.py, tests/handlers/wallet/bridge_information/show/test_wallet_bridge_information_show.py
=> ALIS-2709: Add WalletBridgeInformationShow API

permission-template.yaml
=> ALIS-2948: Fix WalletBridgeInformationShow API

api-template.yaml
=> ALIS-2949: Fix MeWalletTokenHistoriesIndex API

requirements.txt
* セキュリティパッチを当てるため、該当ライブラリのバージョンを更新
=> ALIS-3002: Update requiment.txt

api-template.yaml, src/handlers/me/wallet/token/send/me_wallet_token_send.py, tests/handlers/me/wallet/token/send/test_me_wallet_token_send.py
=> Fix return value for token send

swagger/swagger.yaml
* swaggerファイルの定義を追加
* No
* なし
* ALISユーザー
- サーバレス
- フロントエンド
- プライベートチェーン
* なし 
* swaggerの定義が足りておらず、APIが叩けない状態になっていたので定義を追加した
* なし
* なし
* なし
* 考慮する必要なし
* アラームが必要か
* 不要
* 不要
=> ALIS-3336: Fix to add swagger definition

src/handlers/me/applications/delete/me_applications_delete.py, src/handlers/me/applications/show/me_applications_show.py, src/handlers/me/applications/update/me_applications_update.py, tests/handlers/me/applications/delete/test_me_applications_delete.py, tests/handlers/me/applications/show/test_me_applications_show.py, tests/handlers/me/applications/update/test_me_applications_update.py
* https://github.com/AlisProject/serverless-application/pull/281#discussion_r278790713
* の指摘の内容で、私が以前出した部分でも対応できていなかったので対応いたしました。
* 必須パラメータの追加
* テストの修正
* 不要なロギング処理が残っていたので削除しました。
=> Make be required client_id

swagger/swagger.yaml
=> ALIS-3439: Fix swagger.yaml

swagger/swagger.yaml
=> ALIS-3452: Fix swagger functions

src/handlers/articles/tip_ranking/handler.py
* ArticlesTipRankingのハンドラー定義が間違っているので修正
=> Fix handler definition of ArticlesTipRanking

database-template.yaml
* database-templateのSucceededTip定義を修正
=> ALIS-3493: Fix database template

src/common/lambda_base.py, tests/common/test_lambda_base.py
=> ALIS-3562: Fix verified string

tests/common/test_lambda_base.py
=> ALIS-3563: Fix check

README.md, api-with-oauth-template.yaml
- テンプレートの構文エラーを修正
- ついでにREADME.mdを少々修正
=> ALIS-3568: Fix wrong templates

.envrc.sample, README.md, fix_api.sh
=> ALIS-3570: Fix fix_api.sh

api-with-oauth-template.yaml, swagger/custom-auth-swagger.yaml
=> Delete Unnecessary APIs.

api-with-oauth-template.yaml, swagger/custom-auth-swagger.yaml
=> ALIS-3574: Remove useless APIs

src/handlers/me/applications/create/me_applications_create.py
アプリケーションタイプの判定が間違っていたため修正。
修正箇所については単体テストでは確認が難しいため、結合テストにて実施
=> Fix type for application

.envrc.sample, README.md, api-with-oauth-template.yaml, fix_api.sh, function-template.yaml, permission-template.yaml, src/common/lambda_base.py, src/common/settings.py, src/handlers/applications/show/applications_show.py, src/handlers/applications/show/handler.py, src/handlers/me/allowed_applications/index/me_allowed_applications_index.py, src/handlers/me/applications/create/me_applications_create.py, src/handlers/me/applications/delete/me_applications_delete.py, src/handlers/me/applications/update/me_applications_update.py, src/handlers/me/wallet/token/send/me_wallet_token_send.py, swagger/custom-auth-swagger.yaml, swagger/swagger.yaml, tests/common/test_lambda_base.py, tests/handlers/applications/show/test_applications_show.py, tests/handlers/me/allowed_applications/index/test_me_allowed_applications_index.py, tests/handlers/me/applications/delete/test_me_applications_delete.py, tests/handlers/me/applications/show/test_me_applications_show.py, tests/handlers/me/applications/update/test_me_applications_update.py, tests/handlers/me/wallet/token/send/test_me_wallet_token_send.py
* 投げ銭ランキングのブランチをdevelopにマージすることに伴い、発生したコンフリクトを解消した
=> ALIS-3592: Resolve conflicts tip ranking

api-template.yaml
* ElasticSearchServiceをapi-template.yamlから削除
=> ALIS-3594: Remove ElasticSearchService

elasticsearch-template.yaml
* elasticsearchのテンプレートに必要なパラメータが追加されていなかったので修正
=> ALIS-3597: Fix to add parameter

src/handlers/me/wallet/tip/me_wallet_tip.py
=> Fix addres for eth

src/handlers/me/wallet/tip/me_wallet_tip.py, tests/handlers/me/wallet/tip/test_me_wallet_tip.py
10進数と16進数で比較してしまっている箇所があったため、 10進数で比較するように修正
=> Fix confirm for tip value

README.md
* Elasticsearch の変更に伴い、README を修正
=> ALIS-3630: Fix README.md

.circleci/config.yml
=> change container heep size

.circleci/config.yml, .gitignore, README.md, exec_test.py
* なぜこの変更をするのか、
- CI実行時間短縮
- 概要
- CIのテストをパラで実行するように修正しました。
=> ALIS-3622: edit CI

.circleci/config.yml
* なぜこの変更をするのか、
- stagingとproductionのデプロイ方法を合わせるため
* 課題は何か、
- stagingとproductionのデプロイ方法が異なり、本番環境で思わぬバグを含む可能性がある
- stagingとproductionのデプロイ方法が同じフローとなる
* 無し
- serverless-applicationをフォークしてCircleCIでビルドする場合は、各自のCircleCIのアカウントで`serverless_staging` というContextを登録する必要がある
* なにをどう変更したか
- `deploy_api.sh` を利用していた部分を、ステージングに合わせて個々のJobへ分割した
本番環境のワークフローは以下の通り。(fix-apiでコケてるのは無視してください)
=> ALIS-3733: edit CI workflow

README.md, make_deploy_zip.py
=> ALIS-3800: add target option to make_deploy.py

.circleci/config.yml
- `config.yml`リファクタリング
- JIRA連携を追加
=> ALIS-3805: edit CI

src/handlers/me/articles/like/create/me_articles_like_create.py, tests/handlers/me/articles/like/create/test_me_articles_like_create.py
* 「セルフいいね」を行った場合に、自分への通知を行わないように修正
なし
- サーバレス
- フロントエンド
* 実施済み
=> ALIS-3824: Update to not notify in case of self like.

database-template.yaml
https://github.com/AlisProject/batch/pull/160
=> add DB stream

api-template.yaml, function-template.yaml, function02-template.yaml, serverless.yml
* なぜこの変更をするのか、
- 分散トレーシングX-Rayの導入
* 課題は何か、
- 問題発生時のトレーサビリティ向上
- リクエスト経路と付随するメタ情報が可視化される
- 変更無し
* なし
- サーバレス
- システムには影響なし
* serverless-applicationのX-Rayを有効にしたので問題発生時にご活用ください
* なにをどう変更したか
- API GWとLambdaでX-Rayを有効可
- API GWとLambdaは自動的にトレース用の情報をX-Rayに送ってくれる
* 使い方の説明
- [X-Ray](https://ap-northeast-1.console.aws.amazon.com/xray/home?region=ap-northeast-1#/service-map)
- [ドキュメント](https://docs.aws.amazon.com/ja_jp/xray/latest/devguide/aws-xray.html)
* なし
* なし
- No
* なし
* なし
* なし
* なし
* アラームが必要か
* 不要
- よりDeepなトレースのための施策
- まずは評価の段階なので
=> enable X-Ray

README.md, create_resource_groups.sh
* なぜこの変更をするのか、
- ログ調査の効率アップ
* 課題は何か、
- リソースが多く、CWのダッシュボードでの一覧表示が困難だった
- https://qiita.com/sot528/items/ae6534114d349d20798d#%E3%83%AA%E3%82%BD%E3%83%BC%E3%82%B9%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97
- 特になし
* CFnがサポートしていないためスクリプトを作成しました。
=> add resource groups

.circleci/config.yml
* なぜこの変更をするのか、
- ロールの定義箇所が変更になったのでワークフローを変更する
* 課題は何か、
- ロールが変更されたときワークフローが失敗する
- ロールが更新されてもワークフローが失敗しないようになる
Laboがコケてるのは気にしないでください。石井環境で試しておりタイミングがバッティングしたためです。
* No
- https://alismedia.atlassian.net/browse/ALIS-4036
* 影響を与えるユーザは誰か
- dev
- サーバレス
- CI/CDのみ
* 特になし  
* なにをどう変更したか
- CircleCIのワークフローを変更
* 使い方の説明
* バグの場合は再現条件
* なし
* なし
- No
- 無い
- 無い
- ある
- あるとしたらその修正をCIへ反映したか
- 今回の修正はこれがメイン
* なし
- production (模擬的に確認)
- staging
- 上記以外
- function02とapiの間に依存関係が無いため並列処理にしています。その観点で問題ないかご確認ください
* マージしていただきましたら石井まで声をおかけください
=> fix other env CD pipeline

serverless.yml, src/handlers/labo/n/majority_judgement/create/majority_judgement_create.py, src/handlers/labo/n/majority_judgement/delete_all/handler.py, src/handlers/labo/n/majority_judgement/delete_all/majority_judgement_delete_all.py
https://github.com/AlisProject/frontend-application/pull/939
=> fix for new MJ project

elasticsearch-template.yaml
=> ALIS-4260: Update instancetype for Elasticsearch.

src/common/lambda_base.py, tests/handlers/login/facebook/authorization_url/test_login_facebook_authorization_url.py, tests/handlers/login/facebook/index/test_login_facebook_index.py, tests/handlers/login/twitter/authorization_url/test_login_twitter_authorization_url.py, tests/handlers/login/twitter/index/test_login_twitter_index.py, tests/handlers/login/yahoo/authorization_url/test_login_yahoo_authorization_url.py, tests/handlers/login/yahoo/index/test_login_yahoo_index.py, tests/handlers/me/articles/drafts/article_id/create/test_me_article_drafts_article_id_create.py, tests/handlers/me/articles/drafts/create/test_me_article_drafts_create.py
- https://alismedia.atlassian.net/browse/ALIS-4232
- 本リポジトリ以外は一旦保留
* 問題なければマージしていただき、stgで動作確認後にお知らせください。デプロイいたします。
=> add Class name to exception logs

database-template.yaml, database.yaml
=> ALIS-4294 Add CognitoBackup dynamo table

src/handlers/me/wallet/tip/me_wallet_tip.py
* 投げ銭のバーン分をプールするように修正
* 有： バーン先のアドレスを指定する BurnAddress を追加
* 変更した場合は以下の作業を行う
=> ALIS-4325: Modify burn address.

api-template.yaml, deploy.sh, src/handlers/me/wallet/tip/me_wallet_tip.py
・BurnAddress 追加に伴いテンプレートを修正
・変数の命名規則が既存と異なっていたため修正
=> Add parameter for BurnAddress to template.

src/handlers/me/wallet/token/allhistories/create/me_wallet_token_allhistories_create.py, tests/handlers/me/wallet/token/allhistories/create/test_me_wallet_token_allhistories_create.py
* なぜこの変更をするのか、
* 課題は何か、
* など、この変更に対する概要を記載
* 変更したとしたらどのような変更か
* 変更した場合は以下の作業を行う
* 影響を与えるユーザは誰か
- サーバレス
- フロントエンド
- プライベートチェーン
* 環境構築手順に変更はあるか。
* ある場合は手順を更新: http://bit.ly/30bfDZF
* なにをどう変更したか
* 使い方の説明
* バグの場合は再現条件
* 変更されるクエリはあるか
- あるならどのような変更か
- 変更前: 
- 変更後: 
* 新規に追加されるクエリ
* 観点:
* index周りの指定は適切か
* 想定される対象のデータ量
* 想定されるデータ量が大量のとき大丈夫か (ダメな場合、いつまでにどうにかする予定があるのか、忘れないために別チケットを用意したか)
* ブロックチェーンを参照するか
* ブロックチェーンへのトランザクションが発生するか
- Yes
- 投げ銭におけるワンタイムトークンなど、フロントエンドに対してフェイルセーフな設計となっているか
- No
- 無い
- ある
- あるとしたらその修正内容を[Confluence](https://alismedia.atlassian.net/wiki/x/hICM)にまとめたか
- 無い
- ある
- あるとしたらその修正内容はコード化したか
- 無い
- ある
- あるとしたらその修正をCIへ反映したか
* …
=> Modify a type text from 'get from an user' to 'get from user'

.github/pull_request_template.md, tests/handlers/me/wallet/token/send/test_me_wallet_token_send.py
https://github.com/AlisProject/ssm/pull/17
- 本リポジトリはほぼ影響の無いテスト修正とPRテンプレートのついでの修正のみです。
=> change daily withdraw max

function02-template.yaml
* 環境変数設定が不足していたため追加（SCREENED_ARTICLE_TABLE_NAME ）
=> ALIS-5056: Add env ScreenedArticleTableName for ArticlesTipRanking

requirements.txt
security fixです。
マージしていただき、ステージング環境で画像の処理周りをざっとご確認ください。その後デプロイいたします。
=> security fix

function02-template.yaml
=> ALIS-5279: Add UserConfigurationsTableName.

package-lock.json, package.json
=> security fix.

database-template.yaml, database.yaml, function02-template.yaml, src/common/settings.py, src/handlers/users/articles/popular/handler.py, src/handlers/users/articles/popular/users_articles_popular.py, tests/handlers/users/articles/popular/test_users_articles_popular.py
=> Add users_articles_popular.

permission-template.yaml, swagger/swagger.yaml
* swagger と permission の設定に UsersArticlesPopular を追加
=> ALIS-5769: Add UsersArticlesPopular to swagger and permission.

docker-compose.yml, src/handlers/me/wallet/token/allhistories/create/me_wallet_token_allhistories_create.py, tests/handlers/me/wallet/token/allhistories/create/test_me_wallet_token_allhistories_create.py
* CSV ダウンロードで種別が unknown と判定される場合があるバグに対応
* private_eth_address に大文字が含まれる場合に発生していたため種別を小文字で判定するように修正
* 該当パターンで実施できることを追加
* locakstack が version 11.5 より下位互換が無い修正が入っていたためバージョンを11.4で固定
https://github.com/localstack/localstack/releases/tag/v0.11.5
- 内容を確認し、問題なければマージしてください。
=> ALIS-5803: Fix bug that all types to unknown.

src/handlers/me/wallet/token/allhistories/create/me_wallet_token_allhistories_create.py, tests/handlers/me/wallet/token/allhistories/create/test_me_wallet_token_allhistories_create.py
* 一部データが反映されていないバグがあったため対応
* カストディ対応以前のアドレスでの取得が漏れていたため、対応
=> Fix bug with data is missing for old address.

src/handlers/cognito_trigger/postconfirmation/post_confirmation.py, tests/handlers/cognito_trigger/postconfirmation/test_post_confirmation.py
* パスワード変更時に例外が発生し処理が中断してしまう問題があったため修正   
* パスワード変更時には不要な処理を実行しようとして例外を発生させていたため、パスワード変更の場合は処理を中断する処理を追加
=> ALIS-5961: UpdateCognitoTriggerBase to LambdaBase in post_confirmation.

src/handlers/me/wallet/token/allhistories/create/me_wallet_token_allhistories_create.py, tests/handlers/me/wallet/token/allhistories/create/test_me_wallet_token_allhistories_create.py
* CSVダウンロードデータに不要なレコードが存在したため削除
* 移行時に発生するデータは不要なためCSVには出力しないように修正
=> ALIS-5936: Fixed a bug that unnecessary data existed.

src/handlers/me/external_provider_user/create/me_external_provider_user_create.py, tests/handlers/me/external_provider_user/create/test_me_external_provider_user_create.py
* 既にアカウントを保有しているユーザがサードパーティでのアカウントを作成しようとすると例外が発生し、かつ一部ログイン情報が欠落する場合がある。
=> ALIS-5909:  Fix a bug that caused deletion when run by an existing user.

function02-template.yaml, permission-template.yaml, requirements.txt, src/handlers/me/articles/drafts/delete/handler.py, src/handlers/me/articles/drafts/delete/me_articles_drafts_delete.py, swagger/swagger.yaml, tests/handlers/me/articles/drafts/delete/test_me_articles_drafts_delete.py
=> Add api of delete_draft.

api-template.yaml, deploy.sh, src/common/settings.py, src/common/twitter_util.py, src/handlers/me/articles/like/create/me_articles_like_create.py, tests/handlers/me/articles/like/create/test_me_articles_like_create.py, tests/tests_common/tests_util.py
=> Add tweet process.

function02-template.yaml, permission-template.yaml, src/common/es_util.py, src/common/settings.py, src/handlers/search/tags_count/handler.py, src/handlers/search/tags_count/search_tags_count.py, swagger/swagger.yaml, tests/handlers/search/tags_count/test_search_tags_count.py
=> Add search tags count.

src/common/es_util.py, src/handlers/search/tags_count/search_tags_count.py
*人気ゲームランキングで件数が正しく集計されないケースが存在したため修正。
=> Fix count bug for ranking.

api-template.yaml, deploy.sh, src/common/exceptions.py, src/common/settings.py, src/common/tag_util.py, src/common/web3_util.py, src/handlers/me/articles/drafts/publish/me_articles_drafts_publish.py, src/handlers/me/articles/drafts/publish_with_header/me_articles_drafts_publish_with_header.py, src/handlers/me/articles/public/republish/me_articles_public_republish.py, src/handlers/me/articles/public/republish_with_header/me_articles_public_republish_with_header.py, tests/common/test_tag_util.py, tests/common/test_web3_util.py, tests/handlers/me/articles/drafts/publish/test_me_articles_drafts_publish.py, tests/handlers/me/articles/drafts/publish_with_header/test_me_articles_drafts_publish_with_header.py, tests/handlers/me/articles/public/republish/test_me_articles_public_republish.py, tests/handlers/me/articles/public/republish_with_header/test_me_articles_public_republish_with_header.py, tests/tests_common/tests_util.py
=> Add badge validate process for tag.
